<p>Lekka pilarka spalinowa ze sprawdzonymi rozwiązaniami technicznymi STIHL. Doskonała do przygotowania drewna opałowego
    i prac budowlanych w drewnie. Wyposażona w boczny napinacz piły łańcuchowej oraz oszczędny silnik 2-MIX. Prowadnica
    o długości 35 cm pozwala ścinać nawet grubsze gałęzie.
</p>
<p><b>DANE TECHNICZNE</b></p>
<ul class="ul">
    <li>Moc kW/KM: 1,4/1,9</li>
    <li>Pojemność skokowa cm³: 31,8</li>
    <li>Długość prowadnicy cm:</li>
    <li>Ciężar kg 1): 4,1</li>
    <li>Ciężar zestawu kg 2): 4,78</li>
    <li>Stosunek ciężaru do mocy kg/kW: 3</li>
    <li>Podziałka piły łańcuchowej: 3/8 " P</li>
    <li>Wartość drgań strona lewa / prawa m/s² 3): 6,6/7,8</li>
    <li>Poziom mocy akustycznej dB(A) 4): 112</li>
    <li>Poziom ciśnienia akustycznego dB(A) 4): 100</li>
</ul>
<p><b>Silnik STIHL 2-MIX</b></p>
<p>Dwusuwowy silnik STIHL w technologii 2-MIX zapewnia dużą moc, a przy tym oszczędność zużycia paliwa do 20% w
    porównaniu do dwusuwowych silników STIHL o podobnej mocy bez technologii 2-MIX. Emisja spalin spada o ok. 50%
</p>
<p><b>Czterokanałowa technika STIHL</b></p>
<p>W czterech kanałach przelotowych następuje zawirowanie mieszanki paliwowo-powietrznej przed zapłonem. Zapewnia to
    lepsze spalanie paliwa i znacznie podnosi sprawność silnika. Skutek: mniejsze zużycie paliwa i wysoki moment
    obrotowy w szerokim przedziale obrotów.
</p>
<p><b>Kompensator</b></p>
<p>Wyczyszczenie filtra staje się konieczne dopiero wtedy, gdy moc silnika wyraźnie spadnie. Umieszczony w gaźniku
    kompensator STIHL sprawia, że pomimo wzrostu zanieczyszczenia filtra powietrza moc silnika, zawartość substancji
    szkodliwych w spalinach oraz zużycie paliwa przez dłuższy czas pozostają stałe. W ten sposób możliwa jest dłuższa
    praca bez konieczności przeprowadzania czynności serwisowych.
</p>
<p><b>System antywibracyjny</b></p>
<p>Mocne wibracje przenoszone przez uchwyty urządzeń mechanicznych mogą prowadzić do choroby wibracyjnej. Z tego powodu
    STIHL stworzył system antywibracyjny. W urządzeniach mechanicznych wyposażonych w system AV strefy uchwytów znacznie
    redukują liczbę drgań wytwarzanych przez silnik spalinowy i pracujące narzędzie.
</p>
<p><b>Wielofunkcyjny przełącznik</b></p>
<p>Obsługa wszystkich ważnych funkcji pilarki, takich jak rozruch na ciepło i na zimno, praca i wyłączanie odbywa się za
    pomocą jednej dźwigni. Rozwiązanie to zapewnia wyjątkowy komfort i bezpieczeństwo obsługi, ponieważ prawa ręka przez
    cały czas spoczywa na uchwycie
</p>
<p><b>Boczny napinacz piły łańcuchowej</b></p>
<p>Śruba napinacza obracana jest specjalnym pokrętłem przechodzącym przez pokrywę koła napędowego piły łańcuchowej.
    Umożliwia to uniknięcie kontaktu dłoni z ostrą piłą łańcuchową i ostrymi zębami zderzaka oporowego.
</p>
<p><b>STIHL Ematic-System</b></p>
<p>System STIHL Ematic składa się z prowadnicy Ematic, piły łańcuchowej Oilomatic oraz pompy olejowej z regulacją
    wydajności wzgl. redukcją ilości tłoczonego oleju. Specjalna konstrukcja prowadnicy i piły łańcuchowej sprawia, że
    każda kropla oleju dociera dokładnie w te miejsca piły łańcuchowej, gdzie jest najbardziej potrzebna. Umożliwia to
    redukcję zużycia oleju smarującego piłę łańcuchową do 50%.
</p>
<br/>
