<?php

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
/** @var Slider $sliderViewModel */

use GardenLawn\Core\Utils\Utils;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\View\Element\Template;

$sliderViewModel = $viewModels->require(Slider::class);
global $works, $galleries, $worksAsset;
$imgExt = Utils::getImageExtForBrowser();
try {
    $mediaUrl = Utils::getMediaUrl();
} catch (NoSuchEntityException $e) {

}
try {
    $works = Utils::getWorksMediaGalleryAsset();
    $galleries = [];
    foreach ($works as $work) {
        $galleries[] = $work['name'];
    }
    $galleries = array_unique($galleries);
} catch (NoSuchEntityException $e) {

}

$worksInfo = [];
$j = 1;
foreach ($galleries as $key) {
    $images = [];
    foreach ($works as $k => $w) {
        if (str_contains($w['path'], 'gallery/' . $key . '/')) {
            $w['thumb'] = str_replace('gallery/', '.thumbsgallery/', $w['link']);
            $images[] = $w;
        }
    }
    $gallery = [
        'id' => $key,
        'key' => floor($j / 2) + $j % 2,
        'images' => $images
    ];
    $worksInfo [] = $gallery;
    $j++;
}

?>
<link rel="stylesheet" type="text/css"
      href="/static/frontend/GardenLawn/Hyvatheme/pl_PL/css/slider-pro.css" media="screen"/>
<?php $hyvaCsp->registerInlineScript() ?>
<?php $hyvaCsp->registerInlineScript() ?>
<div x-data="gardenLawnCoreGallery">
<?php /** Moved variables previously here to "./view/frontend/templates/gallery-csp-js.phtml" */ ?>
<?php /** References (`$worksInfo`) */ ?>
</div><?php $hyvaCsp->registerInlineScript() ?>
<div id="sliders" class="gallery-grid">
    <div class="row">
    </div>
</div>
<?php $hyvaCsp->registerInlineScript() ?>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCoreGallery() {
    return Object.assign(
        viewFrontendTemplatesGalleryMovedScript0.call(this)
    )
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCoreGallery', gardenLawnCoreGallery), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>