<?php

declare(strict_types=1);

use GardenLawn\Core\ViewModel\Gallery;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

$galleryViewModel = $viewModels->require(Gallery::class);
$worksInfo = $galleryViewModel->getWorksInfo();

?>
<link rel="stylesheet" type="text/css"
      href="<?= $escaper->escapeUrl($block->getViewFileUrl('css/slider-pro.css')) ?>" media="screen"/>

<div
    x-data='{
        galleries: <?= json_encode($worksInfo, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>,
        initSlider(id) {
            $(id).sliderPro({
                imageScaleMode: "contain",
                arrows: true,
                fadeArrows: false,
                fullscreen: true,
                fadeFullscreen: false,
                buttons: false,
                waitForLayers: true,
                autoplay: false,
                autoScaleLayers: false,
                thumbnailHeight: 50,
                thumbnailsPosition: "bottom",
                thumbnailPointer: false,
                thumbnailArrows: true,
                fadeThumbnailArrows: false,
                thumbnailTouchSwipe: true,
                fullScreen: true
            }).resize();

            let slider = $(id);
            let fullscreen = slider.find(".sp-full-screen-button");
            fullscreen.css("display", "none");
            slider.find(".sp-slide").on("click", function () {
                if (!slider.hasClass("sp-swiping")) {
                    fullscreen.trigger("click");
                }
            });
        }
    }'
    id="sliders"
    class="gallery-grid"
>
    <div class="row">
        <template x-for="item in galleries" :key="item.id">
            <div class="text-center gallery-div column div-bordered-blue" style="margin:5px;">
                <h3 class="text-2xl font-medium text-gray-900 title-font text-center" x-text="item.id"></h3>
                <div class="slider-pro" :id="'my-slider-' + item.id" x-init="initSlider('#my-slider-' + item.id)">
                    <div class="sp-slides">
                        <template x-for="image in item.images" :key="image.link">
                            <div class="sp-slide">
                                <img class="sp-image"
                                     :data-src="image.link"
                                     :alt="image.title"
                                     :height="image.height"
                                     :width="image.width" />
                            </div>
                        </template>
                    </div>
                    <div class="sp-thumbnails">
                        <template x-for="image in item.images" :key="image.link">
                            <img class="sp-thumbnail"
                                 :src="image.thumb"
                                 :alt="image.title"
                                 :height="image.height"
                                 :width="image.width" />
                        </template>
                    </div>
                </div>
            </div>
        </template>
    </div>
</div>
