<?php declare(strict_types=1);

/** @var Template $block */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\View\Element\Template;

$sliderViewModel = $block->getData('sliderViewModel');
if (!$sliderViewModel) {
    // Fallback if not passed via layout
    /** @var ViewModelRegistry $viewModels */
    $viewModels = ObjectManager::getInstance()->get(ViewModelRegistry::class);
    $sliderViewModel = $viewModels->require(Slider::class);
}

$itemsVideo1 = [
    ['divId' => 'gardenlighting_video1', 'videoId' => '53Iz2uHDYrE'],
    ['divId' => 'gardenlighting_video2', 'videoId' => 'RBrzXBKfZ9s'],
    ['divId' => 'gardenlighting_video3', 'videoId' => 'UtSeV5e1fjU'],
    ['divId' => 'gardenlighting_video4', 'videoId' => 'iGyPUnknuWA']
];

$videoGroups = [$itemsVideo1];

$itemsTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$sliderTemplate = 'GardenLawn_Core::slider-php.phtml';

?>
<div class="div-bordered-blue flex flex-col gap-6">
    <?php foreach ($videoGroups as $group): ?>
        <?php if (!empty($group)): ?>
            <div class="video-slider-container">
                <?= $sliderViewModel->getSliderForItems($itemsTemplate, $group, $sliderTemplate)
                    ->setData('max_visible', 1)
                    ->setData('maybe_purged_tailwind_slide_item_classes', 'w-full')
                    ->setData('maybe_purged_tailwind_section_classes', 'text-gray-700 body-font')
                    ->toHtml() ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
