<?php declare(strict_types=1);

/** @var Template $block */

use Magento\Framework\View\Element\Template;

$itemsVideo1 = [
    ['divId' => 'gardenlighting_video1', 'videoId' => '53Iz2uHDYrE'],
    ['divId' => 'gardenlighting_video2', 'videoId' => 'RBrzXBKfZ9s'],
    ['divId' => 'gardenlighting_video3', 'videoId' => 'UtSeV5e1fjU'],
    ['divId' => 'gardenlighting_video4', 'videoId' => 'iGyPUnknuWA']
];
?>
<div class="lg:w-1/3">
    <div class="div-bordered-blue flex flex-col gap-6">
        <?php foreach ($itemsVideo1 as $videoItem): ?>
            <?= $block->getLayout()
                ->createBlock(Template::class)
                ->setTemplate('GardenLawn_Core::slider-youtube-item.phtml')
                ->setData('item', $videoItem)
                ->toHtml() ?>
        <?php endforeach; ?>
    </div>
</div>
