<?php declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
/** @var Slider $sliderViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$sliderViewModel = $viewModels->require(Slider::class);
$itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$itemsVideo1 = [
    ['divId' => 'gardenlighting_video1', 'videoId' => '53Iz2uHDYrE'],
    ['divId' => 'gardenlighting_video2', 'videoId' => 'RBrzXBKfZ9s'],
    ['divId' => 'gardenlighting_video3', 'videoId' => 'UtSeV5e1fjU'],
    ['divId' => 'gardenlighting_video4', 'videoId' => 'iGyPUnknuWA']
];
?>
<div class="lg:w-1/3">
    <div class="div-bordered-blue">
        <?=
        $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo1)
            //->setData('title', __('Wideo'))
            ->toHtml()
        ?>
    </div>
</div>
