<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** Generated with hyva-csp-helper.php */
?>
<script type="text/javascript" async=""
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/js(1)"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" async=""
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/script.js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>(function (html) {
            html.className = html.className.replace(/\bno-js\b/, 'js')
        })(document.documentElement);</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script data-cfasync="false" data-pagespeed-no-defer="" type="text/javascript">//<![CDATA[
        var gtm4wp_datalayer_name = "dataLayer";
        var dataLayer = dataLayer || [];
        //]]>
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="application/ld+json" class="yoast-schema-graph">{
            "@context": "https://schema.org",
            "@graph": [
                {
                    "@type": "WebSite",
                    "@id": "https://trawnikproducent.pl/#website",
                    "url": "https://trawnikproducent.pl/",
                    "name": "Trawnik Producent",
                    "description": "Trawnik Producent to firma z ponad 25 letni\u0105 tradycj\u0105, specjalizuj\u0105ca si\u0119 w produkcji darni rolowanej na potrzeby zar\u00f3wno klient\u00f3w indywidualnych jak i bran\u017cy budownictwa sportowego.",
                    "potentialAction": [
                        {
                            "@type": "SearchAction",
                            "target": {
                                "@type": "EntryPoint",
                                "urlTemplate": "https://trawnikproducent.pl/?s={search_term_string}"
                            },
                            "query-input": "required name=search_term_string"
                        }
                    ],
                    "inLanguage": "pl-PL"
                },
                {
                    "@type": "WebPage",
                    "@id": "https://trawnikproducent.pl/trawa-ogrodowa/#webpage",
                    "url": "https://trawnikproducent.pl/trawa-ogrodowa/",
                    "name": "TRAWA OGRODOWA - Trawnik Producent",
                    "isPartOf": {
                        "@id": "https://trawnikproducent.pl/#website"
                    },
                    "datePublished": "2024-04-16T09:36:06+00:00",
                    "dateModified": "2024-06-25T14:55:59+00:00",
                    "breadcrumb": {
                        "@id": "https://trawnikproducent.pl/trawa-ogrodowa/#breadcrumb"
                    },
                    "inLanguage": "pl-PL",
                    "potentialAction": [
                        {
                            "@type": "ReadAction",
                            "target": [
                                "https://trawnikproducent.pl/trawa-ogrodowa/"
                            ]
                        }
                    ]
                },
                {
                    "@type": "BreadcrumbList",
                    "@id": "https://trawnikproducent.pl/trawa-ogrodowa/#breadcrumb",
                    "itemListElement": [
                        {
                            "@type": "ListItem",
                            "position": 1,
                            "name": "Strona g\u0142\u00f3wna",
                            "item": "https://trawnikproducent.pl/"
                        },
                        {
                            "@type": "ListItem",
                            "position": 2,
                            "name": "TRAWA OGRODOWA"
                        }
                    ]
                }
            ]
        }</script>
    
<script type="application/ld+json">{
            "@context": "http:\/\/schema.org",
            "@type": "Organization",
            "name": "Trawnik Producent",
            "sameAs": [
                "https:\/\/facebook.com\/TrawnikProducent\/?fref=ts",
                "https:\/\/twitter.com\/trawnikp",
                "https:\/\/youtube.com\/user\/TrawnikPro",
                "https:\/\/facebook.com\/TrawnikProducent\/?fref=ts",
                "https:\/\/twitter.com\/trawnikp",
                "https:\/\/youtube.com\/user\/TrawnikPro"
            ],
            "url": "https:\/\/trawnikproducent.pl\/",
            "logo": "https:\/\/trawnikproducent.pl\/wp-content\/uploads\/cropped-trawnikproducent.png"
        }</script>
    
<script type="application/ld+json">{
            "@context": "http:\/\/schema.org",
            "@type": "Article",
            "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "https:\/\/trawnikproducent.pl\/trawa-ogrodowa\/"
            },
            "headline": "TRAWA OGRODOWA",
            "datePublished": "2024-04-16T11:36:06+0200",
            "dateModified": "2024-06-25T16:55:59+0200",
            "author": {
                "@type": "Person",
                "name": "anna"
            },
            "description": "TRAWNIK OGRODOWY                  TRAWNIK PRODUCENT                  CZYTAJ WI\u0118CEJ...                                                                                                            TRAWA OGRODOWA                                                           Opr\u00f3cz wielko\u015bci plantacji, nasz\u0105 cech\u0105 wyr\u00f3\u017cniaj\u0105c\u0105 jest wysoka jako\u015b\u0107 produkowanej trawy. Wynika to z najwy\u017cszej jako\u015bci zastosowanych materia\u0142\u00f3w produkcyjnych oraz w\u0142a\u015bciwo\u015bci technologicznych plantacji \u2013 jest to jedyna w Polsce plantacja ca\u0142kowicie nawadniana.                                           Posiada ponad 20 km ruroci\u0105g\u00f3w, w\u0142asne studnie g\u0142\u0119binowe oraz zbiorniki retencyjne. Zapewnia to najwy\u017csz\u0105",
            "publisher": {
                "@type": "Organization",
                "name": "Trawnik Producent",
                "logo": {
                    "@type": "ImageObject",
                    "url": "https:\/\/trawnikproducent.pl\/wp-content\/uploads\/cropped-trawnikproducent.png",
                    "width": 240,
                    "height": 138
                }
            }
        }</script>

    
<script type="text/javascript">
        window._wpemojiSettings = {
            "baseUrl": "https:\/\/s.w.org\/images\/core\/emoji\/13.1.0\/72x72\/",
            "ext": ".png",
            "svgUrl": "https:\/\/s.w.org\/images\/core\/emoji\/13.1.0\/svg\/",
            "svgExt": ".svg",
            "source": {"concatemoji": "https:\/\/trawnikproducent.pl\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.8.10"}
        };
        !function (e, a, t) {
            var n, r, o, i = a.createElement("canvas"), p = i.getContext && i.getContext("2d");

            function s(e, t) {
                var a = String.fromCharCode;
                p.clearRect(0, 0, i.width, i.height), p.fillText(a.apply(this, e), 0, 0);
                e = i.toDataURL();
                return p.clearRect(0, 0, i.width, i.height), p.fillText(a.apply(this, t), 0, 0), e === i.toDataURL()
            }

            function c(e) {
                var t = a.createElement("script");
                t.src = e, t.defer = t.type = "text/javascript", a.getElementsByTagName("head")[0].appendChild(t)
            }

            for (o = Array("flag", "emoji"), t.supports = {
                everything: !0,
                everythingExceptFlag: !0
            }, r = 0; r < o.length; r++) t.supports[o[r]] = function (e) {
                if (!p || !p.fillText) return !1;
                switch (p.textBaseline = "top", p.font = "600 32px Arial", e) {
                    case"flag":
                        return s([127987, 65039, 8205, 9895, 65039], [127987, 65039, 8203, 9895, 65039]) ? !1 : !s([55356, 56826, 55356, 56819], [55356, 56826, 8203, 55356, 56819]) && !s([55356, 57332, 56128, 56423, 56128, 56418, 56128, 56421, 56128, 56430, 56128, 56423, 56128, 56447], [55356, 57332, 8203, 56128, 56423, 8203, 56128, 56418, 8203, 56128, 56421, 8203, 56128, 56430, 8203, 56128, 56423, 8203, 56128, 56447]);
                    case"emoji":
                        return !s([10084, 65039, 8205, 55357, 56613], [10084, 65039, 8203, 55357, 56613])
                }
                return !1
            }(o[r]), t.supports.everything = t.supports.everything && t.supports[o[r]], "flag" !== o[r] && (t.supports.everythingExceptFlag = t.supports.everythingExceptFlag && t.supports[o[r]]);
            t.supports.everythingExceptFlag = t.supports.everythingExceptFlag && !t.supports.flag, t.DOMReady = !1, t.readyCallback = function () {
                t.DOMReady = !0
            }, t.supports.everything || (n = function () {
                t.readyCallback()
            }, a.addEventListener ? (a.addEventListener("DOMContentLoaded", n, !1), e.addEventListener("load", n, !1)) : (e.attachEvent("onload", n), a.attachEvent("onreadystatechange", function () {
                "complete" === a.readyState && t.readyCallback()
            })), (n = t.source || {}).concatemoji ? c(n.concatemoji) : n.wpemoji && n.twemoji && (c(n.twemoji), c(n.wpemoji)))
        }(window, document, window._wpemojiSettings);
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/wp-emoji-release.min.js"
        type="text/javascript" defer=""></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/jquery.min.js"
            id="jquery-core-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/jquery-migrate.min.js"
            id="jquery-migrate-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/gtm4wp-contact-form-7-tracker.js"
            id="gtm4wp-contact-form-7-tracker-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/gtm4wp-form-move-tracker.js"
            id="gtm4wp-form-move-tracker-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/script(1).js"
            id="theme-script-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/fc_modal.js"
            id="fc-modal-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/tooltip.min.js"
            id="tooltip-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/awesomplete.min.js"
            id="awesomplete-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/core.min.js"
            id="jquery-ui-core-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/mouse.min.js"
            id="jquery-ui-mouse-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" id="fc-form-js-extra">
        /* <![CDATA[ */
        var FC = {
            "ajaxurl": "https:\/\/trawnikproducent.pl\/wp-admin\/admin-ajax.php",
            "fct": {
                "1w": "1w",
                "1m": "1m",
                "1y": "1y",
                "Form Name": "Form Name",
                "Set Width Option": "Set the widths of two fields to 50% each to fit them in one row.<br>You can have any number of fields in the same row, as long as the sum of widths is 100%",
                "Alt Label": "The field label \/ key to use when sending data via a webhook",
                "Dropdown One": "You can set the value of the options different from the text, using this pattern",
                "Dropdown Two": "Here, 100 would be the value, and Apple would be the text.",
                "keepdata": "Keep Data When Deleting Plugin",
                "needAPIKey": "You need to enter the Google API Key when editing the field to make the autocomplete address field work",
                "Form:": "Form:",
                "Embed Type:": "Embed Type:",
                "Add a FormCraft form": "Add a FormCraft form",
                "Inline": "Inline",
                "Popup": "Popup",
                "Slide In": "Slide In",
                "Button Text:": "Button Text:",
                "Alignment:": "Alignment:",
                "Left": "Left",
                "Center": "Center",
                "Right": "Right",
                "Placement:": "Placement:",
                "Bottom Right": "Bottom Right",
                "Bind:": "Bind:",
                "bind form popup action to a CSS selector": "bind form popup action to a CSS selector",
                "Class:": "Class:",
                "add a custom class to the popup button": "add a custom class to the popup button",
                "Font Color:": "Font Color:",
                "font color of the button": "font color of the button",
                "Button Color:": "Button Color:",
                "color of the button": "color of the button",
                "Auto Popup:": "Auto Popup:",
                "auto popup the form on page load after x seconds": "auto popup the form on page load after x seconds",
                "loseChanges": "You will lose any un-saved changes.",
                "Free AddOns": "Free AddOns",
                "Purchased AddOns": "Purchased AddOns",
                "Paid AddOns": "Paid AddOns",
                "read more": "read more",
                "Nothing Left To Install": "Nothing Left To Install",
                "Please check your internet connection": "Please check your internet connection",
                "back": "back",
                "Help Topics": "Help Topics",
                "Sorry, nothing here": "Sorry, nothing here",
                "Contact Support": "Contact Support",
                "Unknown Error.": "Unknown Error.",
                "Failed Saving.": "Failed Saving.",
                "Failed Saving. Please try disabing your firewall, or security plugin.": "Failed Saving. Please try disabing your firewall, or security plugin.",
                "Debug Info": "Debug Info",
                "Invalid": "Invalid",
                "Min [x] characters required": "Min [x] characters required",
                "Max [x] characters allowed": "Max [x] characters allowed",
                "Max [x] file(s) allowed": "test",
                "Files bigger than [x] MB not allowed": "Files bigger than [x] MB not allowed",
                "Invalid Email": "Invalid Email",
                "Invalid URL": "Invalid URL",
                "Invalid Expression": "Invalid Expression",
                "Only alphabets": "Only alphabets",
                "Only numbers": "Only numbers",
                "Should be alphanumeric": "Should be alphanumeric",
                "Please correct the errors and try again": "Please correct the errors and try again",
                "Message received": "Message received",
                "Email Content Autoresponder": "<p>Hello [Name],<\/p><p><br><\/p><p>We have received your submission. Here are the details you have submitted to us:<\/p><p>[Form Content]<\/p><p><br><\/p><p>Regards,<\/p><p>Nishant<\/p>",
                "Thank you for your submission": "Thank you for your submission",
                "<p>Hello,<\/p><p><br><\/p><p>You have received a new form submission for the form [Form Name]. Here are the details:<\/p><p>[Form Content]<\/p><p><br><\/p><p>Page: [URL]<br>Unique ID: #[Entry ID]<br>Date: [Date]<br>Time: [Time]<\/p>": "<p>Hello,<\/p><p><br><\/p><p>You have received a new form submission for the form [Form Name]. Here are the details:<\/p><p>[Form Content]<\/p><p><br><\/p><p>Page: [URL]<br>Unique ID: #[Entry ID]<br>Date: [Date]<br>Time: [Time]<\/p>",
                "New Form Submission": "New Form Submission",
                "Heading": "Heading",
                "Some Title": "Some Title",
                "Name": "Name",
                "your full name": "your full name",
                "Password": "Password",
                "check your caps": "check your caps",
                "Email": "Email",
                "a valid email": "a valid email",
                "Comments": "Comments",
                "more details": "more details",
                "Favorite Fruits": "Favorite Fruits",
                "pick one!": "pick one!",
                "Language": "Language",
                "Date": "Date",
                "of appointment": "of appointment",
                "Add some text or <strong>HTML<\/strong> here": "Add some text or HTML here",
                "Text Field": "Text Field",
                "Submit Form": "Submit Form",
                "File": "File",
                "upload": "upload",
                "Slider": "Slider",
                "take your pick": "take your pick",
                "Time": "Time",
                "Address": "Address",
                "your home \/ office": "your home \/ office",
                "Rate": "Rate",
                "our support": "our support",
                "Liked the food?": "Liked the food?",
                "let us know": "let us know",
                "Survey": "Survey",
                "How Was the Food?": "How Was the Food?",
                "How Was the Service?": "How Was the Service?",
                "Poor": "Poor",
                "Average": "Average",
                "Good": "Good",
                "Bad": "Bad",
                "Could be better": "Could be better",
                "So so": "So so",
                "Excellent": "Excellent",
                "Blank": "Blank",
                "Template": "Template",
                "Duplicate": "Duplicate",
                "Import": "Import",
                "(blank form)": "(blank form)",
                "80% Zoom": "80% Zoom",
                "Select Form Template To View": "Select Form Template To View",
                "Select Form": "Select Form",
                "Create Form": "Create Form",
                "No Forms Found": "No Forms Found",
                "Forms": "Forms",
                "New Form": "New Form",
                "ID": "ID",
                "Last Edit": "Last Edit",
                "Sure? This action can't be reversed.": "Sure? This action can&#039;t be reversed.",
                "Form Analytics": "Form Analytics",
                "reset analytics data": "reset analytics data",
                "Custom": "Custom",
                "All Forms": "All Forms",
                "form views": "form views",
                "submissions": "submissions",
                "conversion": "conversion",
                "charges": "charges",
                "No Entries Found": "No Entries Found",
                "Select Form to Export": "Select Form to Export",
                "Separator:": "Separator:",
                "Comma (CSV format)": "Comma (CSV format)",
                "Semicolon": "Semicolon",
                "Export": "Export",
                "Entries": "Entries",
                "(All Forms)": "(All Forms)",
                "Created": "Created",
                "Hide Empty Fields": "Hide Empty Fields",
                "Save Changes": "Save Changes",
                "Edit Entry": "Edit Entry",
                "Print": "Print",
                "Referer": "Referer",
                "Insights": "Insights",
                "Get Insights": "Get Insights",
                "Period": "Period",
                "All": "All",
                "From": "From",
                "To": "To",
                "Max Entries": "Max Entries",
                "Entries Analyzed": "Entries Analyzed",
                "No Insights Available": "No Insights Available",
                "learn more": "learn more",
                "License Key verified": "License Key verified",
                "Verified": "Verified",
                "Update Key Info": "Update Key Info",
                "Verify Key": "Verify Key",
                "Purchased On": "Purchased On",
                "Last Check": "Last Check",
                "Expires On": "Expires On",
                "More Info": "More Info",
                "days too late": "days too late",
                "days left": "days left",
                "Renew License Key": "Renew License Key",
                "renewing the license key gives you access to auto plugin updates and free customer support": "renewing the license key gives you access to auto plugin updates and free customer support",
                "No Files Found": "No Files Found",
                "File Uploads": "File Uploads",
                "Trash": "Trash",
                "Type": "Type",
                "Size": "Size",
                "Disable Analytics": "Disable Analytics",
                "Search": "Search",
                "Loading": "Loading",
                "Entry View": "Entry View",
                "Your License Key": "Your License Key",
                "Your Email": "Your Email"
            },
            "datepickerLang": "https:\/\/trawnikproducent.pl\/wp-content\/plugins\/formcraft3\/assets\/js\/datepicker-lang\/"
        };
        /* ]]> */
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/form.min.js"
            id="fc-form-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>

        (function ($) {
            if (!$) return;
            $(document).on("show_variation", function (event, variant) {
                if (!variant.is_in_stock) return;
                window.nudgify.product({
                    id: variant.variation_id || null,
                    stock: variant.max_qty || null,
                    image: variant.image.thumb_src || null,
                })
            });
        })(window.jQuery || null);
        (function (w) {
            var k = "nudgify", n = w[k] || (w[k] = {});
            n.uuid = "e54c3088-7d1c-43f5-8951-2c0076975a05";
            var d = document, s = d.createElement("script");
            s.src = "https:\/\/pixel.nudgify.com\/pixel.js";
            s.async = 1;
            s.charset = "utf-8";
            d.getElementsByTagName("head")[0].appendChild(s)
        })(window)
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/pixel.js"
        async="" charset="utf-8"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script data-cfasync="false" data-pagespeed-no-defer="" type="text/javascript">//<![CDATA[
        var dataLayer_content = {"pagePostType": "page", "pagePostType2": "single-page", "pagePostAuthor": "anna"};
        dataLayer.push(dataLayer_content);//]]>
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script data-cfasync="false">//<![CDATA[
        (function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                '//www.googletagmanager.com/gtm.' + 'js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-TVQ5PV');//]]>
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>
        if (!document.querySelector("meta[name='viewport")) {
            var vpMeta = document.createElement('meta');
            vpMeta.name = "viewport";
            vpMeta.content = "width=device-width, initial-scale=1.0";
            document.getElementsByTagName('head')[0].appendChild(vpMeta);
        }
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/banner.js"
        async="" id="cookieyes-banner"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript">
    /* <![CDATA[ */
    var FC_Validation_8 = {
        "is_required": "Required",
        "is_invalid": "Invalid",
        "min_char": "Min [x] characters required",
        "max_char": "Max [x] characters allowed",
        "min_files": "Min [x] file(s) required",
        "max_files": "Max [x] file(s) allowed",
        "max_file_size": "Files bigger than [x] MB not allowed",
        "allow_email": "Invalid Email",
        "allow_url": "Invalid URL",
        "allow_regexp": "Invalid Expression",
        "allow_alphabets": "Only alphabets",
        "allow_numbers": "Only numbers",
        "allow_alphanumeric": "Should be alphanumeric",
        "failed": "Wprowadzono b\u0142\u0119dne dane."
    };
    /* ]]> */
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/regenerator-runtime.min.js"
        id="regenerator-runtime-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/wp-polyfill.min.js"
        id="wp-polyfill-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" id="">!function (b, e, f, g, a, c, d) {
        b.fbq || (a = b.fbq = function () {
            a.callMethod ? a.callMethod.apply(a, arguments) : a.queue.push(arguments)
        }, b._fbq || (b._fbq = a), a.push = a, a.loaded = !0, a.version = "2.0", a.queue = [], c = e.createElement(f), c.async = !0, c.src = g, d = e.getElementsByTagName(f)[0], d.parentNode.insertBefore(c, d))
    }(window, document, "script", "https://connect.facebook.net/en_US/fbevents.js");
    fbq("init", "1268885870147671");
    fbq("track", "PageView");</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" id="contact-form-7-js-extra">
    /* <![CDATA[ */
    var wpcf7 = {"api": {"root": "https:\/\/trawnikproducent.pl\/wp-json\/", "namespace": "contact-form-7\/v1"}};
    /* ]]> */
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/index.js"
        id="contact-form-7-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/api.js"
        id="google-recaptcha-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" id="wpcf7-recaptcha-js-extra">
    /* <![CDATA[ */
    var wpcf7_recaptcha = {
        "sitekey": "6LfvLgcUAAAAAPOOh86keTygF9gUFEczbi_tjWxQ",
        "actions": {"homepage": "homepage", "contactform": "contactform"}
    };
    /* ]]> */
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/index(1).js"
        id="wpcf7-recaptcha-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/wp-embed.min.js"
        id="wp-embed-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>
    jQuery(document).ready(function () {


    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script async="" charset="UTF-8"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_4/pl.js"></script>
<?php $hyvaCsp->registerInlineScript() ?>
