<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** Generated with hyva-csp-helper.php */
?>
<script type="text/javascript" async=""
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/js(1)"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" async=""
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/script.js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>(function (html) {
            html.className = html.className.replace(/\bno-js\b/, 'js')
        })(document.documentElement);</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script data-cfasync="false" data-pagespeed-no-defer="" type="text/javascript">//<![CDATA[
        var gtm4wp_datalayer_name = "dataLayer";
        var dataLayer = dataLayer || [];
        //]]>
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="application/ld+json" class="yoast-schema-graph">{
            "@context": "https://schema.org",
            "@graph": [
                {
                    "@type": "WebSite",
                    "@id": "https://trawnikproducent.pl/#website",
                    "url": "https://trawnikproducent.pl/",
                    "name": "Trawnik Producent",
                    "description": "Trawnik Producent to firma z ponad 25 letni\u0105 tradycj\u0105, specjalizuj\u0105ca si\u0119 w produkcji darni rolowanej na potrzeby zar\u00f3wno klient\u00f3w indywidualnych jak i bran\u017cy budownictwa sportowego.",
                    "potentialAction": [
                        {
                            "@type": "SearchAction",
                            "target": {
                                "@type": "EntryPoint",
                                "urlTemplate": "https://trawnikproducent.pl/?s={search_term_string}"
                            },
                            "query-input": "required name=search_term_string"
                        }
                    ],
                    "inLanguage": "pl-PL"
                },
                {
                    "@type": "WebPage",
                    "@id": "https://trawnikproducent.pl/logistyka/#webpage",
                    "url": "https://trawnikproducent.pl/logistyka/",
                    "name": "LOGISTYKA - Trawnik Producent",
                    "isPartOf": {
                        "@id": "https://trawnikproducent.pl/#website"
                    },
                    "datePublished": "2024-04-17T22:43:25+00:00",
                    "dateModified": "2024-06-20T10:04:01+00:00",
                    "breadcrumb": {
                        "@id": "https://trawnikproducent.pl/logistyka/#breadcrumb"
                    },
                    "inLanguage": "pl-PL",
                    "potentialAction": [
                        {
                            "@type": "ReadAction",
                            "target": [
                                "https://trawnikproducent.pl/logistyka/"
                            ]
                        }
                    ]
                },
                {
                    "@type": "BreadcrumbList",
                    "@id": "https://trawnikproducent.pl/logistyka/#breadcrumb",
                    "itemListElement": [
                        {
                            "@type": "ListItem",
                            "position": 1,
                            "name": "Strona g\u0142\u00f3wna",
                            "item": "https://trawnikproducent.pl/"
                        },
                        {
                            "@type": "ListItem",
                            "position": 2,
                            "name": "LOGISTYKA"
                        }
                    ]
                }
            ]
        }</script>
    
<script type="application/ld+json">{
            "@context": "http:\/\/schema.org",
            "@type": "Organization",
            "name": "Trawnik Producent",
            "sameAs": [
                "https:\/\/facebook.com\/TrawnikProducent\/?fref=ts",
                "https:\/\/twitter.com\/trawnikp",
                "https:\/\/youtube.com\/user\/TrawnikPro",
                "https:\/\/facebook.com\/TrawnikProducent\/?fref=ts",
                "https:\/\/twitter.com\/trawnikp",
                "https:\/\/youtube.com\/user\/TrawnikPro"
            ],
            "url": "https:\/\/trawnikproducent.pl\/",
            "logo": "https:\/\/trawnikproducent.pl\/wp-content\/uploads\/cropped-trawnikproducent.png"
        }</script>
    
<script type="application/ld+json">{
            "@context": "http:\/\/schema.org",
            "@type": "Article",
            "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "https:\/\/trawnikproducent.pl\/logistyka\/"
            },
            "headline": "LOGISTYKA",
            "datePublished": "2024-04-18T00:43:25+0200",
            "dateModified": "2024-06-20T12:04:01+0200",
            "author": {
                "@type": "Person",
                "name": "anna"
            },
            "description": "TRANSPORT         CZYTAJ WI\u0118CEJ...                                                                                                            TRAWNIK PRODUCENT                                      Posiadamy 25-letniedo\u015bwiadczenie w bran\u017cy                                      Prosto z plantacji na palety transportowe trafia trawa zawini\u0119ta w rolk\u0119  i niemal natychmiast \u0142adowana jest do samochodu dostawcy. Dzi\u0119ki temu  nie zwi\u0119kszamy czasu, w kt\u00f3rym trawa pozbawiona jest gruntu.                                           Wysy\u0142amy nasz\u0105 traw\u0119 na wskazany adres na terenie ca\u0142ej Polski oraz poza jej granicami. W",
            "publisher": {
                "@type": "Organization",
                "name": "Trawnik Producent",
                "logo": {
                    "@type": "ImageObject",
                    "url": "https:\/\/trawnikproducent.pl\/wp-content\/uploads\/cropped-trawnikproducent.png",
                    "width": 240,
                    "height": 138
                }
            }
        }</script>

    
<script type="text/javascript">
        window._wpemojiSettings = {
            "baseUrl": "https:\/\/s.w.org\/images\/core\/emoji\/13.1.0\/72x72\/",
            "ext": ".png",
            "svgUrl": "https:\/\/s.w.org\/images\/core\/emoji\/13.1.0\/svg\/",
            "svgExt": ".svg",
            "source": {"concatemoji": "https:\/\/trawnikproducent.pl\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.8.10"}
        };
        !function (e, a, t) {
            var n, r, o, i = a.createElement("canvas"), p = i.getContext && i.getContext("2d");

            function s(e, t) {
                var a = String.fromCharCode;
                p.clearRect(0, 0, i.width, i.height), p.fillText(a.apply(this, e), 0, 0);
                e = i.toDataURL();
                return p.clearRect(0, 0, i.width, i.height), p.fillText(a.apply(this, t), 0, 0), e === i.toDataURL()
            }

            function c(e) {
                var t = a.createElement("script");
                t.src = e, t.defer = t.type = "text/javascript", a.getElementsByTagName("head")[0].appendChild(t)
            }

            for (o = Array("flag", "emoji"), t.supports = {
                everything: !0,
                everythingExceptFlag: !0
            }, r = 0; r < o.length; r++) t.supports[o[r]] = function (e) {
                if (!p || !p.fillText) return !1;
                switch (p.textBaseline = "top", p.font = "600 32px Arial", e) {
                    case"flag":
                        return s([127987, 65039, 8205, 9895, 65039], [127987, 65039, 8203, 9895, 65039]) ? !1 : !s([55356, 56826, 55356, 56819], [55356, 56826, 8203, 55356, 56819]) && !s([55356, 57332, 56128, 56423, 56128, 56418, 56128, 56421, 56128, 56430, 56128, 56423, 56128, 56447], [55356, 57332, 8203, 56128, 56423, 8203, 56128, 56418, 8203, 56128, 56421, 8203, 56128, 56430, 8203, 56128, 56423, 8203, 56128, 56447]);
                    case"emoji":
                        return !s([10084, 65039, 8205, 55357, 56613], [10084, 65039, 8203, 55357, 56613])
                }
                return !1
            }(o[r]), t.supports.everything = t.supports.everything && t.supports[o[r]], "flag" !== o[r] && (t.supports.everythingExceptFlag = t.supports.everythingExceptFlag && t.supports[o[r]]);
            t.supports.everythingExceptFlag = t.supports.everythingExceptFlag && !t.supports.flag, t.DOMReady = !1, t.readyCallback = function () {
                t.DOMReady = !0
            }, t.supports.everything || (n = function () {
                t.readyCallback()
            }, a.addEventListener ? (a.addEventListener("DOMContentLoaded", n, !1), e.addEventListener("load", n, !1)) : (e.attachEvent("onload", n), a.attachEvent("onreadystatechange", function () {
                "complete" === a.readyState && t.readyCallback()
            })), (n = t.source || {}).concatemoji ? c(n.concatemoji) : n.wpemoji && n.twemoji && (c(n.twemoji), c(n.wpemoji)))
        }(window, document, window._wpemojiSettings);
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/wp-emoji-release.min.js"
        type="text/javascript" defer=""></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/jquery.min.js"
            id="jquery-core-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/jquery-migrate.min.js"
            id="jquery-migrate-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/gtm4wp-contact-form-7-tracker.js"
            id="gtm4wp-contact-form-7-tracker-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/gtm4wp-form-move-tracker.js"
            id="gtm4wp-form-move-tracker-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
            src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/script(1).js"
            id="theme-script-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>

        (function ($) {
            if (!$) return;
            $(document).on("show_variation", function (event, variant) {
                if (!variant.is_in_stock) return;
                window.nudgify.product({
                    id: variant.variation_id || null,
                    stock: variant.max_qty || null,
                    image: variant.image.thumb_src || null,
                })
            });
        })(window.jQuery || null);
        (function (w) {
            var k = "nudgify", n = w[k] || (w[k] = {});
            n.uuid = "e54c3088-7d1c-43f5-8951-2c0076975a05";
            var d = document, s = d.createElement("script");
            s.src = "https:\/\/pixel.nudgify.com\/pixel.js";
            s.async = 1;
            s.charset = "utf-8";
            d.getElementsByTagName("head")[0].appendChild(s)
        })(window)
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/pixel.js"
        async="" charset="utf-8"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script data-cfasync="false" data-pagespeed-no-defer="" type="text/javascript">//<![CDATA[
        var dataLayer_content = {"pagePostType": "page", "pagePostType2": "single-page", "pagePostAuthor": "anna"};
        dataLayer.push(dataLayer_content);//]]>
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script data-cfasync="false">//<![CDATA[
        (function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                '//www.googletagmanager.com/gtm.' + 'js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-TVQ5PV');//]]>
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>
        if (!document.querySelector("meta[name='viewport")) {
            var vpMeta = document.createElement('meta');
            vpMeta.name = "viewport";
            vpMeta.content = "width=device-width, initial-scale=1.0";
            document.getElementsByTagName('head')[0].appendChild(vpMeta);
        }
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

<script
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/banner.js"
        async="" id="cookieyes-banner"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/regenerator-runtime.min.js"
        id="regenerator-runtime-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/wp-polyfill.min.js"
        id="wp-polyfill-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" id="contact-form-7-js-extra">
    /* <![CDATA[ */
    var wpcf7 = {"api": {"root": "https:\/\/trawnikproducent.pl\/wp-json\/", "namespace": "contact-form-7\/v1"}};
    /* ]]> */
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/index.js"
        id="contact-form-7-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/api.js"
        id="google-recaptcha-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" id="wpcf7-recaptcha-js-extra">
    /* <![CDATA[ */
    var wpcf7_recaptcha = {
        "sitekey": "6LfvLgcUAAAAAPOOh86keTygF9gUFEczbi_tjWxQ",
        "actions": {"homepage": "homepage", "contactform": "contactform"}
    };
    /* ]]> */
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/index(1).js"
        id="wpcf7-recaptcha-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/wp-embed.min.js"
        id="wp-embed-js"></script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>
    jQuery(document).ready(function () {

    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script type="text/javascript" id="">!function (b, e, f, g, a, c, d) {
        b.fbq || (a = b.fbq = function () {
            a.callMethod ? a.callMethod.apply(a, arguments) : a.queue.push(arguments)
        }, b._fbq || (b._fbq = a), a.push = a, a.loaded = !0, a.version = "2.0", a.queue = [], c = e.createElement(f), c.async = !0, c.src = g, d = e.getElementsByTagName(f)[0], d.parentNode.insertBefore(c, d))
    }(window, document, "script", "https://connect.facebook.net/en_US/fbevents.js");
    fbq("init", "1268885870147671");
    fbq("track", "PageView");</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script async="" charset="UTF-8"
        src="/static/frontend/GardenLawn/Hyvatheme/pl_PL/files/Grass_5/pl.js"></script>
<?php $hyvaCsp->registerInlineScript() ?>
