<?php declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
/** @var Slider $sliderViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$sliderViewModel = $viewModels->require(Slider::class);
$itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$itemsVideo1 = [
    ['divId' => 'video1', 'videoId' => '9B3OeSeHj2E'],
    ['divId' => 'video2', 'videoId' => 'GddYRaUZAR4']
];
?>
<div class="lg:w-1/3">
    <div class="div-bordered-blue">
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo1)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo2 = [
        ['divId' => 'video3', 'videoId' => '2KZ0YCTZD4I'],
        ['divId' => 'video4', 'videoId' => 'vj_3ifs16Cs'],
        ['divId' => 'video5', 'videoId' => 'IkP6xPNSMnU'],
        ['divId' => 'video6', 'videoId' => 'cMbxYqPruSc'],
        ['divId' => 'video7', 'videoId' => 'AaHyRWbYhLc']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo2)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo3 = [
        ['divId' => 'video8', 'videoId' => 'jYrCjkKTfdM'],
        ['divId' => 'video9', 'videoId' => '_-kUrFIZhwE']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo3)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo4 = [
        ['divId' => 'video10', 'videoId' => 'hanGczLa-Yc'],
        ['divId' => 'video11', 'videoId' => 'OW7HKXX-Esc'],
        ['divId' => 'video12', 'videoId' => '271DxnmJ9iw']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo4)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?></div></div>
<div x-data="gardenLawnCoreIrrigationRight">
<?php /** Moved variables previously here to "./view/frontend/templates/irrigation_right-csp-js.phtml" */ ?>
<?php /** References (`$itemsVideo1`, `$video`, `$itemsVideo2`, `$itemsVideo3`, `$itemsVideo4`) */ ?>
</div><?php $hyvaCsp->registerInlineScript() ?>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCoreIrrigationRight() {
    return Object.assign(
        viewFrontendTemplatesIrrigation_rightMovedScript0.call(this)
    )
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCoreIrrigationRight', gardenLawnCoreIrrigationRight), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>