<?php declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Slider $sliderViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$sliderViewModel = $viewModels->require(Slider::class);
$itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$itemsVideo1 = [
    ['divId' => 'video1', 'videoId' => '9B3OeSeHj2E'],
    ['divId' => 'video2', 'videoId' => 'GddYRaUZAR4']
];
?>
<div class="lg:w-1/3">
    <div class="div-bordered-blue">
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo1, 'Magento_Theme::elements/hyva-slider-php.phtml')
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo2 = [
        ['divId' => 'video3', 'videoId' => '2KZ0YCTZD4I'],
        ['divId' => 'video4', 'videoId' => 'vj_3ifs16Cs'],
        ['divId' => 'video5', 'videoId' => 'IkP6xPNSMnU'],
        ['divId' => 'video6', 'videoId' => 'cMbxYqPruSc'],
        ['divId' => 'video7', 'videoId' => 'AaHyRWbYhLc']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo2, 'Magento_Theme::elements/hyva-slider-php.phtml')
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo3 = [
        ['divId' => 'video8', 'videoId' => 'jYrCjkKTfdM'],
        ['divId' => 'video9', 'videoId' => '_-kUrFIZhwE']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo3, 'Magento_Theme::elements/hyva-slider-php.phtml')
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo4 = [
        ['divId' => 'video10', 'videoId' => 'hanGczLa-Yc'],
        ['divId' => 'video11', 'videoId' => 'OW7HKXX-Esc'],
        ['divId' => 'video12', 'videoId' => '271DxnmJ9iw']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo4, 'Magento_Theme::elements/hyva-slider-php.phtml')
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?></div></div>
<script>
    const tag = document.createElement('script');
    tag.src = "https://www.youtube.com/iframe_api";
    const firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    let players = [];

    function onYouTubeIframeAPIReady() {
        <?php foreach ($itemsVideo1 as $video): ?>
        players.push(
            new YT.Player('<?php echo $video['divId']; ?>', {
                videoId: '<?php echo $video['videoId']; ?>',
                events: {
                    'onStateChange': onPlayerStateChange
                }
            }));
        <?php endforeach; ?>

        <?php foreach ($itemsVideo2 as $video): ?>
        players.push(
            new YT.Player('<?php echo $video['divId']; ?>', {
                videoId: '<?php echo $video['videoId']; ?>',
                events: {
                    'onStateChange': onPlayerStateChange
                }
            }));
        <?php endforeach; ?>

        <?php foreach ($itemsVideo3 as $video): ?>
        players.push(
            new YT.Player('<?php echo $video['divId']; ?>', {
                videoId: '<?php echo $video['videoId']; ?>',
                events: {
                    'onStateChange': onPlayerStateChange
                }
            }));
        <?php endforeach; ?>

        <?php foreach ($itemsVideo4 as $video): ?>
        players.push(
            new YT.Player('<?php echo $video['divId']; ?>', {
                videoId: '<?php echo $video['videoId']; ?>',
                events: {
                    'onStateChange': onPlayerStateChange
                }
            }));
        <?php endforeach; ?>
    }

    function onPlayerStateChange(event) {
        for (let i in players) {
            if (event.target.getPlayerState() === YT.PlayerState.PLAYING &&
                players[i].g.id !== event.target.g.id &&
                players[i].getPlayerState() === YT.PlayerState.PLAYING
            ) {
                players[i].stopVideo();
            }
        }
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>
