<?php

declare(strict_types=1);

use GardenLawn\Core\ViewModel\VideoSlider;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$sliderViewModel = $viewModels->require(Slider::class);
$videoSliderViewModel = $viewModels->require(VideoSlider::class);

$videoGroups = [
    [
        ['divId' => 'lawnsseed_video1', 'videoId' => 'azc3snUoxqA'],
        ['divId' => 'lawnsseed_video2', 'videoId' => 'rsTSlYu5wsE'],
        ['divId' => 'lawnsseed_video3', 'videoId' => '1mNrdCVVyMg'],
        ['divId' => 'lawnsseed_video4', 'videoId' => 'ylCKrt8kr0A'],
        ['divId' => 'lawnsseed_video5', 'videoId' => 'ON-2c1UEuxA']
    ],
    [
        ['divId' => 'lawnsseed_video6', 'videoId' => 'jte2HVkgnTI'],
        ['divId' => 'lawnsseed_video7', 'videoId' => 'INEyvPg7f44'],
        ['divId' => 'lawnsseed_video8', 'videoId' => 'R7nQ26mcyu8'],
        ['divId' => 'lawnsseed_video9', 'videoId' => 'ZFK3IFjIlmo']
    ],
    [
        ['divId' => 'lawnsseed_video10', 'videoId' => 'wamsulecYLU']
    ],
    [
        ['divId' => 'lawnsseed_video11', 'videoId' => 'sLMuuN2_e5w']
    ]
];
?>
<div class="md:w-1/3">
    <div class="div-bordered-blue flex flex-col gap-6">
        <?php foreach ($videoGroups as $itemsVideo): ?>
            <?= $block->getLayout()
                ->createBlock(Template::class)
                ->setTemplate('GardenLawn_Core::video-slider.phtml')
                ->setData('sliderViewModel', $sliderViewModel)
                ->setData('videoSliderViewModel', $videoSliderViewModel->setVideoData($itemsVideo))
                ->toHtml() ?>
        <?php endforeach; ?>
    </div>
</div>
