<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Slider $sliderViewModel */

$sliderViewModel = $block->getData('sliderViewModel');
if (!$sliderViewModel) {
    // Fallback if not passed via layout
    /** @var ViewModelRegistry $viewModels */
    $viewModels = ObjectManager::getInstance()->get(ViewModelRegistry::class);
    $sliderViewModel = $viewModels->require(Slider::class);
}

$videoGroups = [
    [
        ['divId' => 'lawnsseed_video1', 'videoId' => 'azc3snUoxqA'],
        ['divId' => 'lawnsseed_video2', 'videoId' => 'rsTSlYu5wsE'],
        ['divId' => 'lawnsseed_video3', 'videoId' => '1mNrdCVVyMg'],
        ['divId' => 'lawnsseed_video4', 'videoId' => 'ylCKrt8kr0A'],
        ['divId' => 'lawnsseed_video5', 'videoId' => 'ON-2c1UEuxA']
    ],
    [
        ['divId' => 'lawnsseed_video6', 'videoId' => 'jte2HVkgnTI'],
        ['divId' => 'lawnsseed_video7', 'videoId' => 'INEyvPg7f44'],
        ['divId' => 'lawnsseed_video8', 'videoId' => 'R7nQ26mcyu8'],
        ['divId' => 'lawnsseed_video9', 'videoId' => 'ZFK3IFjIlmo']
    ],
    [
        ['divId' => 'lawnsseed_video10', 'videoId' => 'wamsulecYLU']
    ],
    [
        ['divId' => 'lawnsseed_video11', 'videoId' => 'sLMuuN2_e5w']
    ]
];

$itemsTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$sliderTemplate = 'GardenLawn_Core::slider-php.phtml';

?>
<div class="div-bordered-blue flex flex-col gap-6">
    <?php foreach ($videoGroups as $group): ?>
        <?php if (!empty($group)): ?>
            <div class="video-slider-container">
                <?= $sliderViewModel->getSliderForItems($itemsTemplate, $group, $sliderTemplate)
                    ->setData('max_visible', 1)
                    ->setData('maybe_purged_tailwind_slide_item_classes', 'w-full')
                    ->setData('maybe_purged_tailwind_section_classes', 'text-gray-700 body-font')
                    ->toHtml() ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
