<?php declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
/** @var Slider $sliderViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$sliderViewModel = $viewModels->require(Slider::class);
$itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$itemsVideo1 = [
    ['divId' => 'video1', 'videoId' => 'azc3snUoxqA'],
    ['divId' => 'video2', 'videoId' => 'rsTSlYu5wsE'],
    ['divId' => 'video3', 'videoId' => '1mNrdCVVyMg'],
    ['divId' => 'video4', 'videoId' => 'ylCKrt8kr0A'],
    ['divId' => 'video5', 'videoId' => 'ON-2c1UEuxA']
];
?>
<div class="md:w-1/3">
    <div class="div-bordered-blue">
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo1)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo2 = [
        ['divId' => 'video6', 'videoId' => 'jte2HVkgnTI'],
        ['divId' => 'video7', 'videoId' => 'INEyvPg7f44'],
        ['divId' => 'video8', 'videoId' => 'R7nQ26mcyu8'],
        ['divId' => 'video9', 'videoId' => 'ZFK3IFjIlmo']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo2)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo3 = [
        ['divId' => 'video10', 'videoId' => 'wamsulecYLU']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo3)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    <?php
    $itemsVideo4 = [
        ['divId' => 'video11', 'videoId' => 'sLMuuN2_e5w']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo4)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?>
    </div>
</div>
<div x-data="gardenLawnCoreLawnsseedRight">
<?php /** Moved variables previously here to "./view/frontend/templates/lawnsseed_right-csp-js.phtml" */ ?>
<?php /** References (`$itemsVideo1`, `$video`, `$itemsVideo2`, `$itemsVideo3`, `$itemsVideo4`) */ ?>
</div><?php $hyvaCsp->registerInlineScript() ?>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCoreLawnsseedRight() {
    return Object.assign(
        viewFrontendTemplatesLawnsseed_rightMovedScript0.call(this)
    )
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCoreLawnsseedRight', gardenLawnCoreLawnsseedRight), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>