<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** Generated with hyva-csp-helper.php */
?>
<script>
    const tag = document.createElement('script');
    tag.src = "https://www.youtube.com/iframe_api";
    const firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    let players = [];

    function onYouTubeIframeAPIReady() {
        <?php foreach ($itemsVideo as $video): ?>
        players.push(
            new YT.Player('<?php echo $video['divId']; ?>', {
                videoId: '<?php echo $video['videoId']; ?>',
                events: {
                    'onStateChange': onPlayerStateChange
                }
            }));
        <?php endforeach; ?>
    }

    function onPlayerStateChange(event) {
        for (let i in players) {
            // Zabezpieczenie przed błędem, jeśli 'players[i]' jest undefined lub nie ma 'g'
            const currentId = players[i]?.g?.id;
            const targetId = event.target?.g?.id;

            if (currentId && targetId && event.target.getPlayerState() === YT.PlayerState.PLAYING &&
                currentId !== targetId &&
                players[i].getPlayerState() === YT.PlayerState.PLAYING
            ) {
                players[i].stopVideo();
            }
        }
    }

    function myXData() {
        return {
            initPhotoSwipe() {
                if (Alpine.store('<?= 'HYVA_PHOTO_SWIPE' ?>').is_loaded) {
                    new PhotoSwipeLightbox({
                        gallery: '#my-gallery',
                        children: 'a',
                        pswpModule: PhotoSwipe
                    }).init();
                }
            }
        }
    }
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCorePoolrobotsRight() {
    return {
        initPhotoSwipe() {
            if (Alpine.store('<?= 'HYVA_PHOTO_SWIPE' ?>').is_loaded) {
                new PhotoSwipeLightbox({
                    gallery: '#my-gallery',
                    children: 'a',
                    pswpModule: PhotoSwipe
                }).init();
            }
        }
    }
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCorePoolrobotsRight', gardenLawnCorePoolrobotsRight), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>
function viewFrontendTemplatesPoolrobots_rightMovedScript0() {
    const el = this.$el,
          wire = this.$wire;
    
    // @todo Implement interaction with the original code ^^
<?php /** Variables from "./view/frontend/templates/poolrobots_right.phtml" */ ?>
<?php /** References (`$itemsVideo`, `$video`) */ ?>
    
    return {
        init() {}
    }
}
window.addEventListener('alpine:init', () => Alpine.data('viewFrontendTemplatesPoolrobots_rightMovedScript0', viewFrontendTemplatesPoolrobots_rightMovedScript0), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>