<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$videoGroups = [
    []
];

$allVideos = [];
foreach ($videoGroups as $group) {
    foreach ($group as $video) {
        $allVideos[] = $video;
    }
}
?>
<div class="div-bordered-blue flex flex-col gap-6">
    <?php foreach ($allVideos as $videoItem): ?>
        <?= $block->getLayout()
            ->createBlock(Template::class)
            ->setTemplate('GardenLawn_Core::slider-youtube-item.phtml')
            ->setData('item', $videoItem)
            ->toHtml() ?>
    <?php endforeach; ?>
</div>
