<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Slider $sliderViewModel */

$sliderViewModel = $block->getData('sliderViewModel');
if (!$sliderViewModel) {
    // Fallback if not passed via layout
    /** @var ViewModelRegistry $viewModels */
    $viewModels = ObjectManager::getInstance()->get(ViewModelRegistry::class);
    $sliderViewModel = $viewModels->require(Slider::class);
}

$videoGroups = [
    []
];

$itemsTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$sliderTemplate = 'GardenLawn_Core::slider-php.phtml';

?>
<div class="div-bordered-blue flex flex-col gap-6">
    <?php foreach ($videoGroups as $group): ?>
        <?php if (!empty($group)): ?>
            <div class="video-slider-container">
                <?= $sliderViewModel->getSliderForItems($itemsTemplate, $group, $sliderTemplate)->toHtml() ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
