<?php declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Slider $sliderViewModel */
/** @var HyvaCsp $hyvaCsp */

use GardenLawn\Core\Utils\Utils;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$imageExt = Utils::getImageExtForBrowser();
$sliderViewModel = $viewModels->require(Slider::class);
$itemsTemplate = 'GardenLawn_Core::slider-item.phtml';
$items = [
    ['imgId' => 'image1', 'src' => Utils::getFileMediaUrl('poolrobots/1')],
    ['imgId' => 'image2', 'src' => Utils::getFileMediaUrl('poolrobots/2')],
    ['imgId' => 'image3', 'src' => Utils::getFileMediaUrl('poolrobots/3')],
    ['imgId' => 'image4', 'src' => Utils::getFileMediaUrl('poolrobots/4')],
    ['imgId' => 'image5', 'src' => Utils::getFileMediaUrl('poolrobots/5')],
    ['imgId' => 'image6', 'src' => Utils::getFileMediaUrl('poolrobots/6')],
    ['imgId' => 'image7', 'src' => Utils::getFileMediaUrl('poolrobots/7')],
    ['imgId' => 'image8', 'src' => Utils::getFileMediaUrl('poolrobots/8')],
    ['imgId' => 'image9', 'src' => Utils::getFileMediaUrl('poolrobots/9')],
    ['imgId' => 'image10', 'src' => Utils::getFileMediaUrl('poolrobots/10')],
    ['imgId' => 'image11', 'src' => Utils::getFileMediaUrl('poolrobots/11')],
    ['imgId' => 'image12', 'src' => Utils::getFileMediaUrl('poolrobots/12')],
    ['imgId' => 'image13', 'src' => Utils::getFileMediaUrl('poolrobots/13')],
    ['imgId' => 'image14', 'src' => Utils::getFileMediaUrl('poolrobots/14')],
    ['imgId' => 'image15', 'src' => Utils::getFileMediaUrl('poolrobots/15')]
];
?>
<div class="md:w-1/3">
    <div class="div-bordered-blue">
    <div id="my-gallery" x-data="gardenLawnCorePoolrobotsRight" x-effect="initPhotoSwipe">
        <?=
        $sliderViewModel->getSliderForItems($itemsTemplate, $items, 'Magento_Theme::elements/hyva-slider-php.phtml')
            ->toHtml()
?>
    </div>
    <?php
    $itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$itemsVideo = [
    ['divId' => 'video1', 'videoId' => 'DcrtcigKCVI'],
    ['divId' => 'video2', 'videoId' => '5mA2IKFv3as'],
    ['divId' => 'video3', 'videoId' => 'La6MkV3uVaU'],
    ['divId' => 'video4', 'videoId' => 'eXzV_fbmdYg'],
    ['divId' => 'video5', 'videoId' => 'Oc6KlNVTqws']
];
?>
    <?=
$sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo, 'Magento_Theme::elements/hyva-slider-php.phtml')
    ->toHtml()
?></div></div>
<script>
    const tag = document.createElement('script');
    tag.src = "https://www.youtube.com/iframe_api";
    const firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    let players = [];

    function onYouTubeIframeAPIReady() {
        <?php foreach ($itemsVideo as $video): ?>
        players.push(
            new YT.Player('<?php echo $video['divId']; ?>', {
                videoId: '<?php echo $video['videoId']; ?>',
                events: {
                    'onStateChange': onPlayerStateChange
                }
            }));
        <?php endforeach; ?>
    }

    function onPlayerStateChange(event) {
        for (let i in players) {
            // Zabezpieczenie przed błędem, jeśli 'players[i]' jest undefined lub nie ma 'g'
            const currentId = players[i]?.g?.id;
            const targetId = event.target?.g?.id;

            if (currentId && targetId && event.target.getPlayerState() === YT.PlayerState.PLAYING &&
                currentId !== targetId &&
                players[i].getPlayerState() === YT.PlayerState.PLAYING
            ) {
                players[i].stopVideo();
            }
        }
    }

    function myXData() {
        return {
            initPhotoSwipe() {
                if (Alpine.store('<?= 'HYVA_PHOTO_SWIPE' ?>').is_loaded) {
                    new PhotoSwipeLightbox({
                        gallery: '#my-gallery',
                        children: 'a',
                        pswpModule: PhotoSwipe
                    }).init();
                }
            }
        }
    }
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCorePoolrobotsRight() {
    return {
        initPhotoSwipe() {
            if (Alpine.store('<?= 'HYVA_PHOTO_SWIPE' ?>').is_loaded) {
                new PhotoSwipeLightbox({
                    gallery: '#my-gallery',
                    children: 'a',
                    pswpModule: PhotoSwipe
                }).init();
            }
        }
    }
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCorePoolrobotsRight', gardenLawnCorePoolrobotsRight), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>
