<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Slider $sliderViewModel */

$sliderViewModel = $block->getData('sliderViewModel');
if (!$sliderViewModel) {
    // Fallback if not passed via layout
    /** @var ViewModelRegistry $viewModels */
    $viewModels = ObjectManager::getInstance()->get(ViewModelRegistry::class);
    $sliderViewModel = $viewModels->require(Slider::class);
}

$videoGroups = [
    [
        ['divId' => 'robots_video1', 'videoId' => '2xkD1WitEmA'],
        ['divId' => 'robots_video2', 'videoId' => 'CBN5-Zz34sg'],
        ['divId' => 'robots_video3', 'videoId' => 'A16e-8aXlSk'],
        ['divId' => 'robots_video4', 'videoId' => 'sgnQuQ-Nebw'],
        ['divId' => 'robots_video5', 'videoId' => 'AgC3QZkDnkw'],
        ['divId' => 'robots_video6', 'videoId' => 'mOtl03bLAvc'],
        ['divId' => 'robots_video7', 'videoId' => 'RGLBv5yA-1g'],
        ['divId' => 'robots_video8', 'videoId' => 'rESVsjTBBHA'],
        ['divId' => 'robots_video9', 'videoId' => 'UJk_yMx38QY']
    ]
    // Second group removed as all videos were private
];

$itemsTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$sliderTemplate = 'GardenLawn_Core::slider-php.phtml';

?>
<div class="div-bordered-blue flex flex-col gap-6">
    <?php foreach ($videoGroups as $group): ?>
        <?php if (!empty($group)): ?>
            <div class="video-slider-container">
                <?= $sliderViewModel->getSliderForItems($itemsTemplate, $group, $sliderTemplate)->toHtml() ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
