<?php declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
/** @var Slider $sliderViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$sliderViewModel = $viewModels->require(Slider::class);
$itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$itemsVideo1 = [
    ['divId' => 'video1', 'videoId' => '2xkD1WitEmA'],
    ['divId' => 'video2', 'videoId' => 'CBN5-Zz34sg'],
    ['divId' => 'video3', 'videoId' => 'A16e-8aXlSk'],
    ['divId' => 'video4', 'videoId' => 'sgnQuQ-Nebw'],
    ['divId' => 'video5', 'videoId' => 'AgC3QZkDnkw'],
    ['divId' => 'video6', 'videoId' => 'mOtl03bLAvc'],
    ['divId' => 'video7', 'videoId' => 'RGLBv5yA-1g'],
    ['divId' => 'video8', 'videoId' => 'rESVsjTBBHA'],
    ['divId' => 'video9', 'videoId' => 'UJk_yMx38QY']
];
?>
<div class="lg:w-1/3">
    <div class="div-bordered-blue">
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo1)
        ->toHtml()
    ?>
    <?php
    $itemsVideo2 = [
        ['divId' => 'video11', 'videoId' => 'Nl7enJVBEeQ'],
        ['divId' => 'video12', 'videoId' => 'WUwCissmzEU'],
        ['divId' => 'video13', 'videoId' => 's2Lav7uQ8SI'],
        ['divId' => 'video14', 'videoId' => 'AmWDTrcegUg'],
        ['divId' => 'video15', 'videoId' => 't7mzpyDXM5M'],
        ['divId' => 'video16', 'videoId' => 'igPgUH1x1sc'],
        ['divId' => 'video17', 'videoId' => 'p9zGsa3JMec'],
        ['divId' => 'video18', 'videoId' => 'fVtu6JBtsZw'],
        ['divId' => 'video19', 'videoId' => 'EF-EPpnqxoA']
    ];
    ?>
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo2)
        ->toHtml()
    ?></div></div>
<div x-data="gardenLawnCoreRobotsRight">
<?php /** Moved variables previously here to "./view/frontend/templates/robots_right-csp-js.phtml" */ ?>
<?php /** References (`$itemsVideo1`, `$video`, `$itemsVideo2`) */ ?>
</div><?php $hyvaCsp->registerInlineScript() ?>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCoreRobotsRight() {
    return Object.assign(
        viewFrontendTemplatesRobots_rightMovedScript0.call(this)
    )
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCoreRobotsRight', gardenLawnCoreRobotsRight), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>