<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$videoGroups = [
    [
        ['divId' => 'robots_video1', 'videoId' => '2xkD1WitEmA'],
        ['divId' => 'robots_video2', 'videoId' => 'CBN5-Zz34sg'],
        ['divId' => 'robots_video3', 'videoId' => 'A16e-8aXlSk'],
        ['divId' => 'robots_video4', 'videoId' => 'sgnQuQ-Nebw'],
        ['divId' => 'robots_video5', 'videoId' => 'AgC3QZkDnkw'],
        ['divId' => 'robots_video6', 'videoId' => 'mOtl03bLAvc'],
        ['divId' => 'robots_video7', 'videoId' => 'RGLBv5yA-1g'],
        ['divId' => 'robots_video8', 'videoId' => 'rESVsjTBBHA'],
        ['divId' => 'robots_video9', 'videoId' => 'UJk_yMx38QY']
    ]
    // Second group removed as all videos were private
];

$allVideos = [];
foreach ($videoGroups as $group) {
    foreach ($group as $video) {
        $allVideos[] = $video;
    }
}
?>
<div class="lg:w-1/3">
    <div class="div-bordered-blue flex flex-col gap-6">
        <?php foreach ($allVideos as $videoItem): ?>
            <?= $block->getLayout()
                ->createBlock(Template::class)
                ->setTemplate('GardenLawn_Core::slider-youtube-item.phtml')
                ->setData('item', $videoItem)
                ->toHtml() ?>
        <?php endforeach; ?>
    </div>
</div>
