<?php declare(strict_types=1);

/** @var Template $block */

use Magento\Framework\View\Element\Template;

$item = $block->getData('item');
?>

<a
    href="<?= $item['src'] ?>"
    class="relative flex items-center bg-white a-cover"
    tabindex="-1">
    <div class="absolute top-0 left-0 flex flex-wrap content-center w-full h-full p-2
                    overflow-hidden align-center hover:shadow-sm">
        <img class="self-center w-full h-auto img-cover"
             src="<?= $item['src'] ?>"
             alt=""
            <?= !str_contains($item['src'], '1.') ? 'loading="lazy"' : '' ?>
             loading="lazy"
        />
    </div>
</a>
