<?php

declare(strict_types=1);

use GardenLawn\Core\ViewModel\VideoSlider;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var VideoSlider $videoSliderViewModel */
/** @var Slider $sliderViewModel */

$videoSliderViewModel = $block->getData('videoSliderViewModel');
$sliderViewModel = $block->getData('sliderViewModel');
$itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';

?>
<div x-data="gardenLawnCoreVideoSlider" data-hyvacsp1='<?= $videoSliderViewModel->getJsonVideoData() ?>' x-init="gardenLawnCoreVideoSliderInit17">
    <?= $sliderViewModel->getSliderForItems($itemsVideoTemplate, $videoSliderViewModel->getVideoData())->toHtml() ?>
</div>
