INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (1, 47, 0, 6, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (2, 50, 0, 6, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (3, 51, 0, 6, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (4, 47, 0, 7, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (5, 50, 0, 7, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (6, 51, 0, 7, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (7, 47, 0, 3, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (8, 50, 0, 3, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (9, 51, 0, 3, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (10, 47, 0, 9, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (11, 50, 0, 9, 'kompleksowe, zakładanie ogrodów, doradztwo, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (12, 51, 0, 9, 'Kompleksowo zakładamy ogrody i tereny zielone. Wszystkie prace realizujemy na najwyższym poziomie z wykorzystaniem najwyższej jakości maszyn ogrodniczych');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (13, 47, 0, 10, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (14, 50, 0, 10, 'ogrody, tereny zielone, projektowanie, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (15, 51, 0, 10, 'Świadczymy usługi projektowania ogrodów oraz doradztwa we współpracy z najlepszymi projektantami architektury krajobrazu dla każdej wielkości terenu lub działki');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (16, 47, 0, 11, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (17, 50, 0, 11, 'projektowanie, systemy nawadniania, ogrody, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (18, 51, 0, 11, 'Projektujemy systemy nawadniania terenów zielonych zgodnie ze sztuką zalecaną przez producenta. Projektujemy systemy każdej wielkości ze sterowaniem pogodowym');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (19, 47, 0, 12, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (20, 50, 0, 12, 'nawadnianie, hunter, hydrawise, rainbird, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (21, 51, 0, 12, 'Montaż systemów nawadniania producentów: Hunter, Hydrawise, RainBird. Wszystkie systemy nawadniania wykonujemy zgodnie ze sztuką zalecaną przez producenta');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (22, 47, 0, 13, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (23, 50, 0, 13, 'barenbrug, trawnik z siewu, trawa, opole, opolskie, polska');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (24, 51, 0, 13, 'Do zakładania przez nas trawników z siewu wykorzystujemy wyłącznie mieszanki producenta Barenbrug. Pielęgnujemy trawniki do całkowitego zadarnienia terenu');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (25, 47, 0, 14, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (26, 50, 0, 14, 'trawa z rolki, trawa, trawnik producent, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (27, 51, 0, 14, 'Specjalizujemy się w zakładaniu trawników z rolki. Jesteśmy oficjalnym dystrybutorem i korzystamy z trawy od największej plantacji w Polsce Trawnik Producent');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (28, 47, 0, 15, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (29, 50, 0, 15, 'siatka na krety, antykret, siatka, krety, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (30, 51, 0, 15, 'Skuteczne, profesjonalne zakładanie siatki przeciw kretom. Zwalczanie kretów. Ochrona przeciw kretom w trawniku. Zakładamy siatki o najwyższej gramaturze');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (31, 47, 0, 16, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (32, 50, 0, 16, 'robot, koszący, kosiarka, ambrogio, techline, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (33, 51, 0, 16, 'Jesteśmy autoryzowanym dystrybutorem robotów koszących Ambrogio oraz TechLine. Świadczymy usługi sprzedaży i montażu robotów koszących, kosiarek automatycznych');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (34, 47, 0, 17, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (35, 50, 0, 17, 'robot basenowy, basen, czyszczenie, nemh2o, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (36, 51, 0, 17, 'Jesteśmy autoryzowanym dystrybutorem robotów basenowych NEMH2O. Świadczymy usługi sprzedaży wraz z montażem i serwisem robotów czyszczących baseny przydomowe');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (37, 47, 0, 18, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (38, 50, 0, 18, 'pielęgnacja ogrodów, zabiegi pielęgnacyjne, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (39, 51, 0, 18, 'Usługi kompleksowej pielęgnacji ogrodów. Wszystkie zabiegi wykonywane są profesjonalnie przy użyciu najwyższej jakości środków ochrony roślin i sprzętów');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (40, 47, 0, 19, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (41, 50, 0, 19, 'oświetlenie, ogród, oczka wodne, światło, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (42, 51, 0, 19, 'Projektujemy i montujemy oświetlenia ogrodów i oczek wodnych z wykorzystaniem produktów najwyższej jakości. Jesteśmy dystrybutorem producenta FX luminaire');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (43, 47, 0, 20, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (44, 50, 0, 20, 'rębak, wycinka, karczowanie, drzew, opole, opolskie, usługi');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (45, 51, 0, 20, 'Zajmujemy się przycinaniem, wycinką drzew o raz karczowaniem terenów');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (46, 47, 0, 21, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (47, 50, 0, 21, 'nasadzenia, drzewa, rośliny, byliny, krzewy, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (48, 51, 0, 21, 'Zajmujemy się każdego rodzaju nasadzeniami: drzewa, krzewy, żywopłoty oraz byliny. Posiadamy profesjonalny sprzęt, aby zasadzić drzewa o większych gabarytach');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (49, 47, 0, 22, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (50, 50, 0, 22, 'koszenie, trawniki, kosiarka, wykaszanie, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (51, 51, 0, 22, 'Zajmujemy się koszeniem zarówno ogrodów przydomowych jak i terenów firmowych oraz publicznych. Do koszenia używamy najwyższej jakości sprzętu m.in. TORO');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (52, 47, 0, 23, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (53, 50, 0, 23, 'niwelacja, wyrównywanie, ziemia przesiewana, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (54, 51, 0, 23, 'Świadczymy usługi związane z pracami ziemnymi oraz wyrównywaniem terenów pod ogrody, nasadzenia, trawniki. Przygotowanie terenu pod wysiew traw i roślin');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (55, 47, 0, 24, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (56, 50, 0, 24, 'ogrodzenia, płoty, montaż ogrodzeń, montaz płotów, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (57, 51, 0, 24, 'Zajmujemy się montażem różnego rodzaju ogrodzeń i płotów');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (58, 47, 0, 25, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (59, 50, 0, 25, 'ekobord, obrzeża, palisady, geokraty, opole, opolskie, kostka');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (60, 51, 0, 25, 'Montaż geokrat i palisad. Wykonywanie obrzeży trawnikowych ekobord z kostki brukowej oraz granitowej. Montaż krawężników oraz innych obrzeży trawnikowych');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (61, 47, 0, 26, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (62, 50, 0, 26, 'krawędziowanie, krawędziarka, eliet edge, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (63, 51, 0, 26, 'Wykonujemy usługi krawędziowania obrzęzy trawnikowych za pomocą profesjonalnej maszyny ELIET Edge Styler Pro wyposażonej w noże o różnych profilach');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (64, 47, 0, 27, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (65, 50, 0, 27, 'usługi brukarskie, kostka brukowa, granit, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (66, 51, 0, 27, 'Wykonujemy usługi brukarskie związane z zakładanymi przez nas ogrodami. Zajmujemy się montażem kostki brukowej i granitowej oraz płyt chodnikowych i krawężników');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (67, 47, 0, 28, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (68, 50, 0, 28, 'zbiornik, deszczówka, szambo, ekologiczne, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (69, 51, 0, 28, 'Nasza firma zajmuje się sprzedażą oraz montażem naziemnych i podziemnych zbiorników na deszczówkę oraz szamb ekologicznych producentów Marseplast oraz GRAF');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (70, 47, 0, 29, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (71, 50, 0, 29, 'stacja uzdatniania wody, odżelaziacz, woda, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (72, 51, 0, 29, 'Nasza firma zajmuje się sprzedażą oraz montażem stacji uzdatniania wody oraz odżelaziaczy do studni głębinowych w celu uzyskania najlepszej jakości wody');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (73, 47, 0, 30, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (74, 50, 0, 30, 'odśnieżanie, śnieg, lód, sól, piasek, zima, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (75, 51, 0, 30, 'Świadczymy usługi odśnieżania posesji klientów oraz obiektów firmowych i parkingów. Dysponujemy do tego niezbędnym sprzętem umożliwiającym sprawny przebieg prac');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (76, 47, 0, 31, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (77, 50, 0, 31, 'galeria, zdjęcia, album, realizacje, opole, opolskie, polska');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (78, 51, 0, 31, 'Prezentacja naszych usług z galerią zdjęć. Zdjęcia wykonanych realizacji. W galerii poszczególnych ogrodów znajdują się zdjęcia ze wszystkich  etapów prac');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (79, 47, 0, 32, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (80, 50, 0, 32, 'cennik, usługi, ogrody, zakładanie ogrodów, opole, opolskie');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (81, 51, 0, 32, 'Zapraszamy do zapoznania się z naszą ofertą');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (85, 47, 0, 34, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (86, 50, 0, 34, 'usługi ogrodnicze, opole, opolskie, zakładanie ogrodów');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (87, 51, 0, 34, 'Oferujemy usługi ogrodnicze w Opolu, w województwie opolskim oraz na terenie kraju. Zakładanie trawników, systemów nawadniania i prace związane z ogrodnictwem\'');
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (88, 47, 0, 35, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (89, 50, 0, 35, null);
INSERT INTO magento.catalog_category_entity_text (value_id, attribute_id, store_id, entity_id, value) VALUES (90, 51, 0, 35, null);
