
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (17, 48, 0, 6, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (18, 49, 0, 6, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (19, 52, 0, 6, 'PRODUCTS');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (20, 60, 0, 6, '2');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (21, 63, 0, 6, '1column');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (24, 48, 0, 7, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (25, 49, 0, 7, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (26, 52, 0, 7, 'PRODUCTS');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (27, 60, 0, 7, '9');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (28, 63, 0, 7, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (30, 48, 0, 3, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (31, 49, 0, 3, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (32, 52, 0, 3, 'PRODUCTS');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (33, 60, 0, 3, '6');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (34, 63, 0, 3, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (35, 120, 0, 3, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (39, 63, 4, 6, '1column');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (41, 45, 0, 8, 'Usługi');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (42, 52, 0, 8, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (43, 63, 0, 8, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (44, 119, 0, 8, 'uslugi');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (45, 120, 0, 8, 'uslugi');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (46, 45, 0, 9, 'Kompleksowe zakładanie ogrodów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (47, 52, 0, 9, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (48, 63, 0, 9, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (49, 119, 0, 9, 'kompleksowe-zakladanie-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (50, 120, 0, 9, 'uslugi/kompleksowe-zakladanie-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (52, 48, 0, 9, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (53, 49, 0, 9, 'Kompleksowe zakładanie ogrodów i wszystkich prac pokrewnych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (54, 60, 0, 9, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (55, 45, 0, 10, 'Projektowanie ogrodów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (56, 52, 0, 10, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (57, 63, 0, 10, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (58, 119, 0, 10, 'projektowanie-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (59, 120, 0, 10, 'uslugi/projektowanie-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (60, 45, 0, 11, 'Projektowanie systemów nawadniania');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (61, 52, 0, 11, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (62, 63, 0, 11, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (63, 119, 0, 11, 'projektowanie-systemow-nawadniania');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (64, 120, 0, 11, 'uslugi/projektowanie-systemow-nawadniania');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (65, 45, 0, 12, 'Systemy nawadniania');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (66, 52, 0, 12, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (67, 63, 0, 12, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (68, 119, 0, 12, 'systemy-nawadniania');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (69, 120, 0, 12, 'uslugi/systemy-nawadniania');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (70, 45, 0, 13, 'Zakładanie trawników z siewu');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (71, 52, 0, 13, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (72, 63, 0, 13, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (73, 119, 0, 13, 'zakladanie-trawnikow-z-siewu');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (74, 120, 0, 13, 'uslugi/zakladanie-trawnikow-z-siewu');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (75, 45, 0, 14, 'Zakładanie trawników z rolki');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (76, 52, 0, 14, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (77, 63, 0, 14, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (78, 119, 0, 14, 'zakladanie-trawnikow-z-rolki');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (79, 120, 0, 14, 'uslugi/zakladanie-trawnikow-z-rolki');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (80, 45, 0, 15, 'Siatka przeciw kretom');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (81, 52, 0, 15, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (82, 63, 0, 15, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (83, 119, 0, 15, 'siatka-przeciw-kretom');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (84, 120, 0, 15, 'uslugi/siatka-przeciw-kretom');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (85, 45, 0, 16, 'Roboty koszące');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (86, 52, 0, 16, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (87, 63, 0, 16, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (88, 119, 0, 16, 'roboty-koszace');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (89, 120, 0, 16, 'uslugi/roboty-koszace');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (90, 45, 0, 17, 'Roboty basenowe');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (91, 52, 0, 17, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (92, 63, 0, 17, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (93, 119, 0, 17, 'roboty-basenowe');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (94, 120, 0, 17, 'uslugi/roboty-basenowe');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (95, 45, 0, 18, 'Pielęgnacja ogrodów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (96, 52, 0, 18, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (97, 63, 0, 18, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (98, 119, 0, 18, 'pielegnacja-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (99, 120, 0, 18, 'uslugi/pielegnacja-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (100, 45, 0, 19, 'Projektowanie oraz montaż oświetlenia');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (101, 52, 0, 19, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (102, 63, 0, 19, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (103, 119, 0, 19, 'projektowanie-oraz-montaz-oswietlenia');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (104, 120, 0, 19, 'uslugi/projektowanie-oraz-montaz-oswietlenia');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (105, 45, 0, 20, 'Wycinka drzew oraz karczowanie terenów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (106, 52, 0, 20, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (107, 63, 0, 20, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (108, 119, 0, 20, 'wycinka-drzew-oraz-karczowanie-terenow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (109, 120, 0, 20, 'uslugi/wycinka-drzew-oraz-karczowanie-terenow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (110, 45, 0, 21, 'Nasadzenia drzew oraz roślin');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (111, 52, 0, 21, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (112, 63, 0, 21, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (113, 119, 0, 21, 'nasadzenia-drzew-oraz-roslin');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (114, 120, 0, 21, 'uslugi/nasadzenia-drzew-oraz-roslin');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (115, 45, 0, 22, 'Koszenie terenów zielonych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (116, 52, 0, 22, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (117, 63, 0, 22, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (118, 119, 0, 22, 'koszenie-terenow-zielonych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (119, 120, 0, 22, 'uslugi/koszenie-terenow-zielonych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (120, 45, 0, 23, 'Prace ziemne niwelacja terenów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (121, 52, 0, 23, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (122, 63, 0, 23, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (123, 119, 0, 23, 'prace-ziemne-niwelacja-terenow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (124, 120, 0, 23, 'uslugi/prace-ziemne-niwelacja-terenow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (125, 45, 0, 24, 'Ogrodzenia, płoty');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (126, 52, 0, 24, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (127, 63, 0, 24, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (128, 119, 0, 24, 'ogrodzenia-ploty');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (129, 120, 0, 24, 'uslugi/ogrodzenia-ploty');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (130, 45, 0, 25, 'Obrzeża, geokraty, palisady');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (131, 52, 0, 25, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (132, 63, 0, 25, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (133, 119, 0, 25, 'obrzeza-geokraty-palisady');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (134, 120, 0, 25, 'uslugi/obrzeza-geokraty-palisady');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (135, 45, 0, 26, 'Krawędziowanie obrzeży trawnika');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (136, 52, 0, 26, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (137, 63, 0, 26, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (138, 119, 0, 26, 'krawedziowanie-obrzezy-trawnika');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (139, 120, 0, 26, 'uslugi/krawedziowanie-obrzezy-trawnika');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (140, 45, 0, 27, 'Prace brukarskie');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (141, 52, 0, 27, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (142, 63, 0, 27, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (143, 119, 0, 27, 'prace-brukarskie');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (144, 120, 0, 27, 'uslugi/prace-brukarskie');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (145, 45, 0, 28, 'Zbiornik na deszczówkę, szamba');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (146, 52, 0, 28, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (147, 63, 0, 28, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (148, 119, 0, 28, 'zbiornik-na-deszczowke-szamba');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (149, 120, 0, 28, 'uslugi/zbiornik-na-deszczowke-szamba');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (150, 45, 0, 29, 'Stacje uzdatniania wody, odżelaziacze');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (151, 52, 0, 29, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (152, 63, 0, 29, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (153, 119, 0, 29, 'stacje-uzdatniania-wody-odzelaziacze');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (154, 120, 0, 29, 'uslugi/stacje-uzdatniania-wody-odzelaziacze');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (155, 45, 0, 30, 'Odśnieżanie');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (156, 52, 0, 30, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (157, 63, 0, 30, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (158, 119, 0, 30, 'odsniezanie');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (159, 120, 0, 30, 'uslugi/odsniezanie');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (162, 48, 0, 10, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (163, 49, 0, 10, 'Profesjonalne doradztwo i projektowanie ogrodów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (164, 60, 0, 10, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (166, 48, 0, 11, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (167, 49, 0, 11, 'Profesjonalne projektowanie systemów nawadniania ogrodów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (168, 60, 0, 11, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (170, 48, 0, 12, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (171, 49, 0, 12, 'Montaż systemów nawadniania Hunter, Hydrawise, RainBird');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (172, 60, 0, 12, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (174, 48, 0, 13, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (175, 49, 0, 13, 'Zakładanie trawników z siewu nasionami producenta Barenbrug');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (176, 60, 0, 13, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (178, 48, 0, 14, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (179, 49, 0, 14, 'Zakładamy trawniki z rolki, z plantacji Trawnik Producent');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (180, 60, 0, 14, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (182, 48, 0, 15, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (183, 49, 0, 15, 'Skuteczne zakładanie siatki przeciw kretom w trawnikach');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (184, 60, 0, 15, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (186, 48, 0, 16, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (187, 49, 0, 16, 'Jesteśmy oficjalnym dystrybutorem robotów koszących Ambrogio');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (188, 60, 0, 16, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (190, 48, 0, 17, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (191, 49, 0, 17, 'Sprzedaż oraz montaż robotów basenowych producenta NemH2O');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (192, 60, 0, 17, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (194, 48, 0, 18, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (195, 49, 0, 18, 'Profesjonalna pielęgnacja ogrodów, dbanie o tereny zielone');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (196, 60, 0, 18, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (198, 48, 0, 19, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (199, 49, 0, 19, 'Projektowanie, montaż oświetlenia ogrodowego i oczek wodnych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (200, 60, 0, 19, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (202, 48, 0, 20, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (203, 49, 0, 20, 'Wycinka drzew oraz karczowanie. Utylizacja za pomocą rębaka');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (204, 60, 0, 20, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (206, 48, 0, 21, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (207, 49, 0, 21, 'Wykonywanie nasadzeń drzew oraz roślin w ogrodach i parkach');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (208, 60, 0, 21, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (210, 48, 0, 22, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (211, 49, 0, 22, 'Świadczymy usługi koszenia trawników oraz terenów zielonych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (212, 60, 0, 22, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (214, 48, 0, 23, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (215, 49, 0, 23, 'Niwelacja terenów pod trawniki, ogrody, nasadzenia');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (216, 60, 0, 23, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (218, 48, 0, 24, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (219, 49, 0, 24, 'Montaż ogrodzeń i płotów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (220, 60, 0, 24, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (222, 48, 0, 25, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (223, 49, 0, 25, 'Montaż obrzeży trawnikowych oraz geokrat ekobord i palisady');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (224, 60, 0, 25, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (226, 48, 0, 26, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (227, 49, 0, 26, 'Krawędziowanie, profilowanie obrzeży trawnika w ogrodach');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (228, 60, 0, 26, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (230, 48, 0, 27, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (231, 49, 0, 27, 'Świadczymy usługi brukarskie związane z architekturą ogrodową');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (232, 60, 0, 27, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (234, 48, 0, 28, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (235, 49, 0, 28, 'Montaż zbiorników na deszczówkę oraz szamb ekologicznych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (236, 60, 0, 28, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (238, 48, 0, 29, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (239, 49, 0, 29, 'Sprzedaż oraz montaż stacji uzdatniania wody i odżelaziaczy');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (240, 60, 0, 29, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (242, 48, 0, 30, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (243, 49, 0, 30, 'Świadczymy usługi odśnieżania posesji prywatnych i parkingów');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (244, 60, 0, 30, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (245, 45, 0, 31, 'Galeria');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (246, 52, 0, 31, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (247, 63, 0, 31, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (248, 119, 0, 31, 'galeria');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (249, 120, 0, 31, 'galeria');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (250, 45, 0, 32, 'Cennik');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (251, 52, 0, 32, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (252, 63, 0, 32, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (253, 119, 0, 32, 'cennik');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (254, 120, 0, 32, 'cennik');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (283, 120, 4, 8, 'uslugi');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (284, 120, 4, 9, 'uslugi/kompleksowe-zakladanie-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (285, 120, 4, 10, 'uslugi/projektowanie-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (286, 120, 4, 11, 'uslugi/projektowanie-systemow-nawadniania');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (287, 120, 4, 12, 'uslugi/systemy-nawadniania');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (288, 120, 4, 13, 'uslugi/zakladanie-trawnikow-z-siewu');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (289, 120, 4, 14, 'uslugi/zakladanie-trawnikow-z-rolki');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (290, 120, 4, 15, 'uslugi/siatka-przeciw-kretom');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (291, 120, 4, 16, 'uslugi/roboty-koszace');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (292, 120, 4, 17, 'uslugi/roboty-basenowe');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (293, 120, 4, 18, 'uslugi/pielegnacja-ogrodow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (294, 120, 4, 19, 'uslugi/projektowanie-oraz-montaz-oswietlenia');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (295, 120, 4, 20, 'uslugi/wycinka-drzew-oraz-karczowanie-terenow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (296, 120, 4, 21, 'uslugi/nasadzenia-drzew-oraz-roslin');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (297, 120, 4, 22, 'uslugi/koszenie-terenow-zielonych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (298, 120, 4, 23, 'uslugi/prace-ziemne-niwelacja-terenow');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (299, 120, 4, 24, 'uslugi/ogrodzenia-ploty');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (300, 120, 4, 25, 'uslugi/obrzeza-geokraty-palisady');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (301, 120, 4, 26, 'uslugi/krawedziowanie-obrzezy-trawnika');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (302, 120, 4, 27, 'uslugi/prace-brukarskie');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (303, 120, 4, 28, 'uslugi/zbiornik-na-deszczowke-szamba');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (304, 120, 4, 29, 'uslugi/stacje-uzdatniania-wody-odzelaziacze');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (305, 120, 4, 30, 'uslugi/odsniezanie');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (307, 48, 0, 31, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (308, 49, 0, 31, 'Galeria zdjęć wykonanych przez nas ogrodów i innych usług');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (309, 60, 0, 31, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (310, 45, 0, 34, 'O nas');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (311, 52, 0, 34, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (312, 63, 0, 34, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (313, 119, 0, 34, 'o-nas');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (314, 120, 0, 34, 'o-nas');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (316, 120, 4, 34, 'o-nas');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (318, 48, 0, 32, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (319, 49, 0, 32, 'Poglądowy cennik oferowanych przez nas usług ogrodniczych');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (320, 60, 0, 32, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (331, 48, 0, 34, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (332, 49, 0, 34, 'Usługi ogrodnicze - Opole, województwo opolskie, Polska');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (333, 60, 0, 34, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (361, 45, 0, 35, 'Kontakt');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (362, 52, 0, 35, 'PAGE');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (363, 63, 0, 35, 'category-full-width');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (364, 119, 0, 35, 'kontakt');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (365, 120, 0, 35, 'kontakt');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (367, 48, 0, 35, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (368, 49, 0, 35, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (369, 60, 0, 35, null);
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (375, 120, 4, 6, 'sprzet');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (376, 120, 4, 7, 'sprzedaz-trawy-w-rolce');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (377, 60, 4, 6, '10');
INSERT INTO magento.catalog_category_entity_varchar (value_id, attribute_id, store_id, entity_id, value) VALUES (378, 60, 4, 7, '9');
