UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/search/engine', value = 'opensearch', updated_at = '2025-04-06 17:27:01' WHERE config_id = 1;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/search/opensearch_server_hostname', value = 'localhost', updated_at = '2025-04-06 17:27:02' WHERE config_id = 2;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/search/opensearch_server_port', value = '9200', updated_at = '2025-04-06 17:27:02' WHERE config_id = 3;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/seo/use_rewrites', value = '1', updated_at = '2025-04-06 17:27:02' WHERE config_id = 4;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/unsecure/base_url', value = 'http://localhost:88/', updated_at = '2025-04-06 17:27:02' WHERE config_id = 5;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/secure/base_url', value = 'http://localhost:88/', updated_at = '2025-04-06 18:06:32' WHERE config_id = 6;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/locale/code', value = 'pl_PL', updated_at = '2025-04-06 17:27:02' WHERE config_id = 7;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/secure/use_in_frontend', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 8;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/secure/use_in_adminhtml', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 9;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/locale/timezone', value = 'Europe/Warsaw', updated_at = '2025-04-06 17:27:03' WHERE config_id = 10;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'currency/options/base', value = 'PLN', updated_at = '2025-04-06 17:27:03' WHERE config_id = 11;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'currency/options/default', value = 'PLN', updated_at = '2025-04-06 17:27:03' WHERE config_id = 12;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'currency/options/allow', value = 'PLN', updated_at = '2025-04-06 17:27:03' WHERE config_id = 13;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'admin/security/use_form_key', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 14;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/region/display_all', value = '1', updated_at = '2025-04-06 17:27:23' WHERE config_id = 15;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/region/state_required', value = 'AL,AR,AU,BY,BO,BR,BG,CA,CL,CN,CO,CR,HR,CZ,DK,EC,EE,GR,GY,IS,IN,IT,LV,LT,MX,PY,PE,PL,PT,RO,ES,SR,SE,CH,UA,US,UY,VE', updated_at = '2025-04-06 17:46:21' WHERE config_id = 16;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/category/root_id', value = '2', updated_at = '2025-04-06 17:27:37' WHERE config_id = 17;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'twofactorauth/duo/application_key', value = 'O018V7eZUID52OMR802toHdCEUMZmBmwxNXwLxEtq6LQXvCVmLICLE1v3bqlxM3t', updated_at = '2025-04-06 17:27:38' WHERE config_id = 18;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'analytics/subscription/enabled', value = '1', updated_at = '2025-04-06 17:27:39' WHERE config_id = 19;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'crontab/default/jobs/analytics_subscribe/schedule/cron_expr', value = '0 * * * *', updated_at = '2025-04-06 17:27:39' WHERE config_id = 20;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'crontab/default/jobs/analytics_collect_data/schedule/cron_expr', value = '00 02 * * *', updated_at = '2025-04-06 17:27:39' WHERE config_id = 21;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'msp_securitysuite_recaptcha/frontend/enabled', value = '0', updated_at = '2025-04-06 17:27:41' WHERE config_id = 22;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'msp_securitysuite_recaptcha/backend/enabled', value = '0', updated_at = '2025-04-06 17:27:41' WHERE config_id = 23;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_base/cron/feeds_refresh', value = '47 * * * *', updated_at = '2025-04-06 17:46:21' WHERE config_id = 24;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_base/cron/daily_send_system_info', value = '14 * * * *', updated_at = '2025-04-06 17:46:21' WHERE config_id = 25;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_base/cron/instance_registration', value = '16 * * * *', updated_at = '2025-04-06 17:46:21' WHERE config_id = 26;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amcustomerexport/admin_email/template', value = '1', updated_at = '2025-04-06 17:27:43' WHERE config_id = 27;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amcustomerimport/admin_email/alert_template', value = '2', updated_at = '2025-04-06 17:27:43' WHERE config_id = 28;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgeoip/refresh_ip_database/cron_schedule', value = '51 3 * * *', updated_at = '2025-04-06 17:46:21' WHERE config_id = 29;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amorderexport/admin_email/template', value = '3', updated_at = '2025-04-06 17:27:43' WHERE config_id = 30;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amorderimport/admin_email/alert_template', value = '4', updated_at = '2025-04-06 17:27:43' WHERE config_id = 31;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amproductexport/admin_email/template', value = '5', updated_at = '2025-04-06 17:27:43' WHERE config_id = 32;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amproductimport/admin_email/alert_template', value = '6', updated_at = '2025-04-06 17:27:44' WHERE config_id = 33;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/seo/product_url_suffix', value = '', updated_at = '2025-04-15 19:43:32' WHERE config_id = 34;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/seo/category_url_suffix', value = '', updated_at = '2025-04-15 19:43:32' WHERE config_id = 35;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'gardenlawn/core/enviroment', value = 'local', updated_at = '2025-04-06 17:46:21' WHERE config_id = 36;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/default/front', value = 'o-nas', updated_at = '2025-04-14 13:47:01' WHERE config_id = 37;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'trans_email/ident_general/email', value = 'marcin.piechota@gardenlawn.pl', updated_at = '2025-04-06 17:46:21' WHERE config_id = 38;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'trans_email/ident_sales/email', value = 'marcin.piechota@gardenlawn.pl', updated_at = '2025-04-06 17:46:21' WHERE config_id = 39;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'trans_email/ident_support/email', value = 'marcin.piechota@gardenlawn.pl', updated_at = '2025-04-06 17:46:21' WHERE config_id = 40;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'trans_email/ident_custom1/email', value = 'marcin.piechota@gardenlawn.pl', updated_at = '2025-04-06 17:46:21' WHERE config_id = 41;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'trans_email/ident_custom2/email', value = 'marcin.piechota@gardenlawn.pl', updated_at = '2025-04-06 17:46:21' WHERE config_id = 42;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/smtp/transport', value = 'smtp', updated_at = '2025-04-06 17:46:21' WHERE config_id = 43;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/smtp/host', value = 'pro2.mail.ovh.net', updated_at = '2025-04-06 17:46:21' WHERE config_id = 44;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/smtp/port', value = '587', updated_at = '2025-04-06 17:46:21' WHERE config_id = 45;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/smtp/username', value = 'marcin.piechota@gardenlawn.pl', updated_at = '2025-04-06 17:46:21' WHERE config_id = 46;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/smtp/ssl', value = 'tls', updated_at = '2025-04-06 17:46:21' WHERE config_id = 47;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/smtp/auth', value = 'login', updated_at = '2025-04-06 17:46:21' WHERE config_id = 48;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'contact/email/recipient_email', value = 'marcin.piechota@gardenlawn.pl', updated_at = '2025-04-06 17:46:21' WHERE config_id = 49;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/customer_login', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 50;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/customer_forgot_password', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 51;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/customer_create', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 52;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/customer_edit', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 53;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/contact', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 54;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/product_review', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 55;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/newsletter', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 56;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/sendfriend', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 57;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/place_order', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 58;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/coupon_code', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 59;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_frontend/type_for/braintree', value = 'recaptcha_v3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 60;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'admin/usage/enabled', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 61;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/full_page_cache/varnish/access_list', value = 'http://gardenlawn.s3.eu-central-1.amazonaws.com', updated_at = '2025-04-06 17:46:21' WHERE config_id = 62;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/full_page_cache/varnish/backend_host', value = 'http://gardenlawn.s3.eu-central-1.amazonaws.com', updated_at = '2025-04-06 17:46:21' WHERE config_id = 63;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/full_page_cache/varnish/backend_port', value = '8080', updated_at = '2025-04-06 17:46:21' WHERE config_id = 64;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/full_page_cache/varnish/grace_period', value = '300', updated_at = '2025-04-06 17:46:21' WHERE config_id = 65;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/unsecure/base_link_url', value = 'http://localhost:88/', updated_at = '2025-04-06 17:46:21' WHERE config_id = 66;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/unsecure/base_static_url', value = '', updated_at = '2025-04-15 15:38:37' WHERE config_id = 67;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/unsecure/base_media_url', value = 'http://gardenlawn.s3.eu-central-1.amazonaws.com/pub/media/', updated_at = '2025-04-06 17:46:21' WHERE config_id = 68;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/secure/base_link_url', value = 'http://localhost:88/', updated_at = '2025-04-06 18:06:32' WHERE config_id = 69;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/secure/base_static_url', value = '', updated_at = '2025-04-15 15:38:37' WHERE config_id = 70;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/secure/base_media_url', value = 'https://gardenlawn.s3.eu-central-1.amazonaws.com/pub/media/', updated_at = '2025-04-06 17:46:21' WHERE config_id = 71;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/secure/enable_hsts', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 72;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/secure/enable_upgrade_insecure', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 73;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/default_layouts/default_product_layout', value = 'product-full-width', updated_at = '2025-04-06 17:46:21' WHERE config_id = 74;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/default_layouts/default_category_layout', value = 'category-full-width', updated_at = '2025-04-06 17:46:21' WHERE config_id = 75;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/default_layouts/default_cms_layout', value = 'cms-full-width', updated_at = '2025-04-06 17:46:21' WHERE config_id = 76;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/cookie/cookie_path', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 77;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/cookie/cookie_domain', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 78;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'web/cookie/cookie_httponly', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 79;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'analytics/general/token', value = 'Zhdtc4u-urNqFoXNf8H9pszo_SBqxH9M9-vZ33mWRt4zCJkqLTd1PYxs6KGwt9Id61X13ZaHZvl_agTrTr_oqQ', updated_at = '2025-04-06 17:46:21' WHERE config_id = 80;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/country/default', value = 'PL', updated_at = '2025-04-06 17:46:21' WHERE config_id = 81;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/country/allow', value = 'PL', updated_at = '2025-04-06 17:46:21' WHERE config_id = 82;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/country/destinations', value = 'PL', updated_at = '2025-04-06 17:46:21' WHERE config_id = 83;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/locale/weight_unit', value = 'kgs', updated_at = '2025-04-06 17:46:21' WHERE config_id = 84;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/locale/firstday', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 85;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/name', value = 'Garden Lawn & Irrigation Marcin Piechota', updated_at = '2025-04-06 17:46:21' WHERE config_id = 86;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/phone', value = '+48 795 997 947', updated_at = '2025-04-06 17:46:21' WHERE config_id = 87;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/hours', value = '24', updated_at = '2025-04-06 17:46:21' WHERE config_id = 88;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/country_id', value = 'PL', updated_at = '2025-04-06 17:46:21' WHERE config_id = 89;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/region_id', value = '1025', updated_at = '2025-04-06 17:46:21' WHERE config_id = 90;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/postcode', value = '46-081', updated_at = '2025-04-06 17:46:21' WHERE config_id = 91;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/city', value = 'Dobrzeń Wielki', updated_at = '2025-04-06 17:46:21' WHERE config_id = 92;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/street_line1', value = 'Namysłowska 2', updated_at = '2025-04-06 17:46:21' WHERE config_id = 93;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/street_line2', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 94;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/store_information/merchant_vat_number', value = '9910370112', updated_at = '2025-04-06 17:46:21' WHERE config_id = 95;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'general/single_store_mode/enabled', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 96;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'admin/dashboard/enable_charts', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 97;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'hyva_react_checkout/general/enable', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 98;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/restrict/allow_ips', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 99;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/debug/template_hints_storefront', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 100;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/debug/template_hints_storefront_show_with_parameter', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 101;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/debug/template_hints_admin', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 102;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/debug/template_hints_blocks', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 103;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'adobe_ims/integration/logging_enabled', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 104;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/template/allow_symlink', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 105;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/translate_inline/active', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 106;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/translate_inline/active_admin', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 107;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/online_customers/online_minutes_interval', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 108;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/online_customers/section_data_lifetime', value = '60', updated_at = '2025-04-06 17:46:21' WHERE config_id = 109;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/address/taxvat_show', value = 'opt', updated_at = '2025-04-06 17:46:21' WHERE config_id = 110;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/address/telephone_show', value = 'opt', updated_at = '2025-04-06 17:46:21' WHERE config_id = 111;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/address/company_show', value = 'opt', updated_at = '2025-04-06 17:46:21' WHERE config_id = 112;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/create_account/vat_frontend_visibility', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 113;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cms/wysiwyg/enabled', value = 'enabled', updated_at = '2025-04-06 17:46:21' WHERE config_id = 114;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cms/pagebuilder/enabled', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 115;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cms/pagebuilder/enable_content_preview', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 116;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cms/pagebuilder/google_maps_api_key', value = null, updated_at = '2025-04-15 15:38:38' WHERE config_id = 117;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cms/pagebuilder/google_maps_style', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 118;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/hyva_breadcrumbs/client_side_enable', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 119;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/address/street_lines', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 120;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/startup/redirect_dashboard', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 121;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'shipping/origin/country_id', value = 'PL', updated_at = '2025-04-06 17:46:21' WHERE config_id = 122;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'shipping/origin/region_id', value = '1025', updated_at = '2025-04-06 17:46:21' WHERE config_id = 123;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'shipping/origin/postcode', value = '46-081', updated_at = '2025-04-06 17:46:21' WHERE config_id = 124;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'shipping/origin/city', value = 'Dobrzeń Wielki', updated_at = '2025-04-06 17:46:21' WHERE config_id = 125;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'shipping/origin/street_line1', value = 'Namysłowska 2', updated_at = '2025-04-06 17:46:21' WHERE config_id = 126;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'shipping/origin/street_line2', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 127;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'shipping/shipping_policy/shipping_policy_content', value = 'My custom Shipping Policy', updated_at = '2025-04-06 17:46:21' WHERE config_id = 128;
UPDATE magento.core_config_data SET scope = 'websites', scope_id = 2, path = 'customer/create_account/vat_frontend_visibility', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 129;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/captcha/enable', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 130;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/captcha/forms', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 131;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/account_information/confirm', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 132;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'login_as_customer/general/enabled', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 133;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cataloginventory/item_options/enable_qty_increments', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 134;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cataloginventory/source_selection_distance_based_google/api_key', value = 'AIzaSyAyqdYA2AZtc5Rqmcdn-0uSvdC5GL8mWtk', updated_at = '2025-04-06 17:46:21' WHERE config_id = 135;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/calculation/cross_border_trade_enabled', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 136;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/defaults/country', value = 'PL', updated_at = '2025-04-06 17:46:21' WHERE config_id = 137;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/defaults/region', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 138;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/defaults/postcode', value = '*', updated_at = '2025-04-06 17:46:21' WHERE config_id = 139;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'checkout/cart/enable_clear_shopping_cart', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 140;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'carriers/instore/active', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 141;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'shipping/shipping_policy/enable_shipping_policy', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 142;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'checkout/cart_link/use_qty', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 143;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/cancellation/enabled', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 144;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/identity/address', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 145;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/identity/logo', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 146;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/identity/logo_html', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 147;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/minimum_order/active', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 148;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/minimum_order/amount', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 149;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/minimum_order/description', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 150;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/minimum_order/error_message', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 151;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/minimum_order/multi_address', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 152;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/minimum_order/multi_address_description', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 153;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'sales/minimum_order/multi_address_error_message', value = 'The current cart does not match multi shipping criteria, please review or contact the store administrator', updated_at = '2025-04-06 17:46:21' WHERE config_id = 154;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'checkout/options/enable_guest_checkout_login', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 155;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'checkout/options/onepage_checkout_enabled', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 156;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'admin/captcha/enable', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 157;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'admin/captcha/forms', value = '', updated_at = '2025-04-06 17:46:21' WHERE config_id = 158;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/create_account/email_domain', value = 'gardenlawn.pl', updated_at = '2025-04-06 17:46:21' WHERE config_id = 159;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'customer/create_account/generate_human_friendly_id', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 160;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/classes/shipping_tax_class', value = '2', updated_at = '2025-04-06 17:46:21' WHERE config_id = 161;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/classes/default_product_tax_class', value = '2', updated_at = '2025-04-06 17:46:21' WHERE config_id = 162;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/classes/default_customer_tax_class', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 163;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/calculation/algorithm', value = 'UNIT_BASE_CALCULATION', updated_at = '2025-04-06 17:46:21' WHERE config_id = 164;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/calculation/based_on', value = 'billing', updated_at = '2025-04-06 17:46:21' WHERE config_id = 165;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/notification/ignore_discount', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 166;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/notification/ignore_price_display', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 167;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/notification/ignore_apply_discount', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 168;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/calculation/price_includes_tax', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 169;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/calculation/shipping_includes_tax', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 170;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/calculation/apply_after_discount', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 171;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/calculation/discount_tax', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 172;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/calculation/apply_tax_on', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 173;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/display/type', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 174;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/display/shipping', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 175;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/cart_display/price', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 176;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/cart_display/subtotal', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 177;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/cart_display/shipping', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 178;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/cart_display/full_summary', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 179;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/cart_display/zero_tax', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 180;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/sales_display/price', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 181;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/sales_display/subtotal', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 182;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/sales_display/shipping', value = '3', updated_at = '2025-04-06 17:46:21' WHERE config_id = 183;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/sales_display/full_summary', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 184;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/sales_display/zero_tax', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 185;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_policy/bar', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 186;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_policy/first_visit_show', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 187;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_policy/log_guest', value = '1', updated_at = '2025-04-06 17:46:21' WHERE config_id = 188;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/cookies_bar_style', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 189;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/notification_text', value = 'Używamy plików cookie, aby ulepszyć nasze usługi, składać oferty osobiste i ulepszać Twoje doświadczenia. Jeśli nie zaakceptujesz opcjonalnych plików cookie poniżej, Twoje doświadczenia mogą być ograniczone. Jeśli chcesz dowiedzieć się więcej, przeczytaj <a href="privacy-policy-cookie-restriction-mode" title="Polityka plików cookie" target="_blank">Politykę plików cookie</a>', updated_at = '2025-04-06 17:46:21' WHERE config_id = 190;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/accept_button/button_text', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 191;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/accept_button/button_order', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 192;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/accept_button/button_color', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 193;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/accept_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 194;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/accept_button/text_color', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 195;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/accept_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:21' WHERE config_id = 196;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/decline_button/enable', value = '0', updated_at = '2025-04-06 17:46:21' WHERE config_id = 197;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/settings_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 198;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/settings_button/button_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 199;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/settings_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 200;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/settings_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 201;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/settings_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 202;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/settings_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 203;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/notification_text', value = 'Używamy plików cookie, aby ulepszyć nasze usługi, składać oferty osobiste i ulepszać Twoje doświadczenia. Jeśli nie zaakceptujesz opcjonalnych plików cookie poniżej, Twoje doświadczenia mogą być ograniczone. Jeśli chcesz dowiedzieć się więcej, przeczytaj <a href="privacy-policy-cookie-restriction-mode" title="Polityka plików cookie" target="_blank">Polityka plików cookie</a>', updated_at = '2025-04-06 17:46:22' WHERE config_id = 204;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/background_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 205;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/policy_text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 206;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/links_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 207;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/group_title_text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 208;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/group_desc_text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 209;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/accept_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 210;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/accept_button/button_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 211;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/accept_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 212;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/accept_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 213;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/accept_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 214;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/accept_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 215;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/decline_button/enable', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 216;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/settings_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 217;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/settings_button/button_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 218;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/settings_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 219;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/settings_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 220;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/settings_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 221;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/settings_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 222;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/notification_text', value = 'Używamy plików cookie, aby ulepszyć nasze usługi, składać oferty osobiste i ulepszać Twoje doświadczenia. Jeśli nie zaakceptujesz opcjonalnych plików cookie poniżej, Twoje doświadczenia mogą być ograniczone. Jeśli chcesz dowiedzieć się więcej, przeczytaj <a href="privacy-policy-cookie-restriction-mode" title="Polityka plików cookie" target="_blank">Politykę plików cookie</a>', updated_at = '2025-04-06 17:46:22' WHERE config_id = 223;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/decline_button/enable', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 224;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/background_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 225;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/group_title_text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 226;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/group_desc_text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 227;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/links_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 228;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/done_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 229;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/done_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 230;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/done_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 231;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/done_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 232;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_settings_bar_customisation/done_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 233;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/general/enabled', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 234;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/general/display_pp_popup', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 235;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/general/country_restrictions', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 236;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/general/log_guest', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 237;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/general/auto_cleaning', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 238;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/privacy_settings_tab_name', value = 'Privacy Settings', updated_at = '2025-04-06 17:46:22' WHERE config_id = 239;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/policies_text_section', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 240;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/download', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 241;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/anonymize', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 242;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/delete', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 243;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/consent_opting', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 244;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/skip_empty_fields', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 245;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/general/excluded_fields', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 246;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/display_dpo_info', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 247;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/customer_access_control/dpo_info', value = 'Jeśli masz jakiekolwiek pytania lub sugestie, skontaktuj się z naszym Inspektorem Ochrony Danych.', updated_at = '2025-04-06 17:46:22' WHERE config_id = 248;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/personal_data/automatic_personal_data_deletion/personal_data_deletion', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 249;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/personal_data/automatic_personal_data_deletion/personal_data_deletion_days', value = '3650', updated_at = '2025-04-06 17:46:22' WHERE config_id = 250;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/personal_data/anonymization_data/personal_data_stored', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 251;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/general/avoid_anonymisation', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 252;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/anonymisation_notification/enable_anonymization_notification', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 253;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/anonymisation_notification/sender', value = 'general', updated_at = '2025-04-06 17:46:22' WHERE config_id = 254;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/anonymisation_notification/reply_to', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 255;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/enable_admin_notification', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 256;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/admin_reciever', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 257;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/enable_approve_deletion_notification', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 258;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/sender', value = 'general', updated_at = '2025-04-06 17:46:22' WHERE config_id = 259;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/reply_to', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 260;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/enable_deny_deletion_notification', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 261;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/deny_sender', value = 'general', updated_at = '2025-04-06 17:46:22' WHERE config_id = 262;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/deny_reply_to', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 263;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/policy_change_notification/enable_policy_change_notification', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 264;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'recaptcha_backend/type_for/user_login', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 265;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'dev/static/sign', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 266;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/productalert_cron/frequency', value = 'D', updated_at = '2025-04-06 17:46:22' WHERE config_id = 267;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'crontab/default/jobs/catalog_product_alert/schedule/cron_expr', value = '0 0 * * *', updated_at = '2025-04-06 17:46:22' WHERE config_id = 268;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'crontab/default/jobs/catalog_product_alert/run/model', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 269;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/productalert_cron/time', value = '00,00,00', updated_at = '2025-04-06 17:46:22' WHERE config_id = 270;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/productalert_cron/error_email', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 271;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/product_video/youtube_api_key', value = null, updated_at = '2025-04-15 19:43:33' WHERE config_id = 272;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/price/scope', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 273;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/search/opensearch_index_prefix', value = 'magento2', updated_at = '2025-04-06 17:46:22' WHERE config_id = 274;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/search/opensearch_enable_auth', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 275;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/search/opensearch_server_timeout', value = '15', updated_at = '2025-04-06 17:46:22' WHERE config_id = 276;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/search/opensearch_minimum_should_match', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 277;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/custom_options/use_calendar', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 278;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/custom_options/year_range', value = ',', updated_at = '2025-04-06 17:46:22' WHERE config_id = 279;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_policy/bar_visibility', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 280;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_policy/auto_cleaning_days', value = '180', updated_at = '2025-04-06 17:46:22' WHERE config_id = 281;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cms/wysiwyg/use_static_urls_in_catalog', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 282;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'checkout/options/enable_agreements', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 283;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/policy_change_notification/sender', value = 'general', updated_at = '2025-04-06 17:46:22' WHERE config_id = 284;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/policy_change_notification/reply_to', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 285;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/cookies_bar_location', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 286;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/background_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 287;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/policy_text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 288;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/links_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 289;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/decline_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 290;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/decline_button/button_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 291;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/decline_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 292;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/decline_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 293;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/decline_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 294;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/classic_bar/decline_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 295;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/policy_text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 296;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/background_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 297;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/links_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 298;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/accept_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 299;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/accept_button/button_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 300;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/accept_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 301;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/accept_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 302;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/accept_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 303;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/accept_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 304;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/decline_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 305;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/decline_button/button_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 306;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/decline_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 307;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/decline_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 308;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/decline_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 309;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/decline_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 310;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/settings_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 311;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/settings_button/button_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 312;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/settings_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 313;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/settings_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 314;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/settings_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 315;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/popup/settings_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 316;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/decline_button/button_text', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 317;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/decline_button/button_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 318;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/decline_button/button_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 319;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/decline_button/button_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 320;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/decline_button/text_color', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 321;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/cookie_bar_customisation/sidebar/decline_button/text_color_hover', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 322;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/consent_mode/enable', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 323;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdprcookie/consent_mode/consent_types', value = '{"item1":{"consent_type":"ad_storage","default_status":"0","cookie_group":"2"},"item2":{"consent_type":"analytics_storage","default_status":"0","cookie_group":"3"},"item3":{"consent_type":"ad_user_data","default_status":"0","cookie_group":"2"},"item4":{"consent_type":"ad_personalization","default_status":"0","cookie_group":"2"}}', updated_at = '2025-04-06 17:46:22' WHERE config_id = 324;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/mysqlmq/successful_messages_lifetime', value = '10080', updated_at = '2025-04-06 17:46:22' WHERE config_id = 325;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/mysqlmq/retry_inprogress_after', value = '1440', updated_at = '2025-04-06 17:46:22' WHERE config_id = 326;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/mysqlmq/failed_messages_lifetime', value = '10080', updated_at = '2025-04-06 17:46:22' WHERE config_id = 327;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/mysqlmq/new_messages_lifetime', value = '10080', updated_at = '2025-04-06 17:46:22' WHERE config_id = 328;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/backup/functionality_enabled', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 329;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/bulk/lifetime', value = '60', updated_at = '2025-04-06 17:46:22' WHERE config_id = 330;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/media_storage_configuration/media_storage', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 331;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/upload_configuration/jpeg_quality', value = '100', updated_at = '2025-04-06 17:46:22' WHERE config_id = 332;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/upload_configuration/enable_resize', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 333;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/media_gallery/enabled', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 334;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/media_gallery_renditions/enabled', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 335;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/media_gallery_renditions/width', value = '1000', updated_at = '2025-04-06 17:46:22' WHERE config_id = 336;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'system/media_gallery_renditions/height', value = '1000', updated_at = '2025-04-06 17:46:22' WHERE config_id = 337;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'adobe_stock/integration/enabled', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 338;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'adobe_ims/integration/admin_enabled', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 339;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'cms/wysiwyg/editor', value = 'mage/adminhtml/wysiwyg/tiny_mce/tinymce5Adapter', updated_at = '2025-04-15 15:38:39' WHERE config_id = 340;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/custom_options/date_fields_order', value = 'y,m,d', updated_at = '2025-04-06 17:46:22' WHERE config_id = 341;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/custom_options/time_format', value = '24h', updated_at = '2025-04-06 17:46:22' WHERE config_id = 342;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'crontab/default/jobs/analytics_update/schedule/cron_expr', value = '0 * * * *', updated_at = '2025-04-06 17:46:22' WHERE config_id = 343;
UPDATE magento.core_config_data SET scope = 'stores', scope_id = 2, path = 'design/theme/theme_id', value = '6', updated_at = '2025-04-15 17:42:58' WHERE config_id = 344;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amasty_gdpr/deletion_notification/admin_sender', value = 'general', updated_at = '2025-04-06 17:46:22' WHERE config_id = 345;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/cart_display/grandtotal', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 346;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'tax/sales_display/grandtotal', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 347;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/general/title', value = 'Mapa strony', updated_at = '2025-04-06 17:46:22' WHERE config_id = 348;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/general/meta_description', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 349;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/general/layout', value = '1column', updated_at = '2025-04-06 17:46:22' WHERE config_id = 350;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/general/show_search_field', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 351;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/general/sort_order', value = '{"links":"Links","categories":"Categories","products":"Products","cms_pages":"CMS pages"}', updated_at = '2025-04-15 15:38:39' WHERE config_id = 352;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/cms/show_cms_pages', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 353;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/cms/cms_title', value = 'Strony', updated_at = '2025-04-06 17:46:22' WHERE config_id = 354;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/cms/column_number', value = '5', updated_at = '2025-04-06 17:46:22' WHERE config_id = 355;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/cms/exclude_cms_pages_values', value = 'no-route,home,enable-cookies,terms|34', updated_at = '2025-04-15 15:38:39' WHERE config_id = 356;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/categories/show_categories', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 357;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/categories/categories_title', value = 'Kategorie', updated_at = '2025-04-06 17:46:22' WHERE config_id = 358;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/categories/exclude', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 359;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/categories/show_as', value = '2', updated_at = '2025-04-06 17:46:22' WHERE config_id = 360;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/categories/column_number', value = '5', updated_at = '2025-04-06 17:46:22' WHERE config_id = 361;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/products/show_products', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 362;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/products/products_title', value = 'Przedmioty', updated_at = '2025-04-06 17:46:22' WHERE config_id = 363;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/products/column_number', value = '5', updated_at = '2025-04-06 17:46:22' WHERE config_id = 364;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/products/split_by_letter', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 365;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/products/hide_out_of_stock', value = '0', updated_at = '2025-04-06 17:46:22' WHERE config_id = 366;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/products/maximum_limit', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 367;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/additional/links_title', value = 'Usługi', updated_at = '2025-04-15 15:38:39' WHERE config_id = 368;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/additional/column_number', value = '5', updated_at = '2025-04-06 17:46:22' WHERE config_id = 369;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amseohtmlsitemap/additional/additional_links', value = 'Kompleksowe zakładanie ogrodów,kompleksowe-zakladanie-ogrodow
Projektowanie ogrodów,projektowanie-ogrodow
Projektowanie systemów nawadniania,projektowanie-systemow-nawadniania
Systemy nawadniania,systemy-nawadniania
Zakładanie trawników z siewu,zakladanie-trawnikow-z-siewu
Zakładanie trawników z rolki,zakladanie-trawnikow-z-rolki
Siatka przeciw kretom,siatka-przeciw-kretom
Roboty koszące,roboty-koszace
Roboty basenowe,roboty-basenowe
Pielęgnacja ogrodów,pielegnacja-ogrodow
Projektowanie oraz montaż oświetlenia,projektowanie-oraz-montaz-oswietlenia
Wycinka drzew oraz karczowanie terenów,wycinka-drzew-oraz-karczowanie-terenow
Nasadzenia drzew oraz roślin,nasadzanie-drzew-oraz-roslin
Koszenie terenów zielonych,koszenie-terenow-zielonych
Prace ziemne niwelacja terenów,prace-ziemne-niwelacja-terenow
Obrzeża, geokraty, palisady,obrzeza-geokraty-palisady
Krawędziowanie obrzeży trawnika,krawedziowanie-obrzezy-trawnika
Prace brukarskie,prace-brukarskie
Zbiornik na deszczówkę, szamba,zbiornik-na-deszczowke
Stacje uzdatniania wody, odżelaziacze,stacje-uzdatniania-wody-odzelaziacze
Odśnieżanie,odsniezanie
Galeria,galeria
Cennik,cennik
Kontakt,kontakt', updated_at = '2025-04-15 15:38:39' WHERE config_id = 370;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'payment/banktransfer/title', value = 'Przelew tradycyjny', updated_at = '2025-04-06 17:46:22' WHERE config_id = 372;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'payment/banktransfer/specificcountry', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 373;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'payment/banktransfer/instructions', value = 'Prosimy o wpłatę na konto nr 16 1140 2004 0000 3302 7889 0739 (mBank) w tytule podając nr zamówienia', updated_at = '2025-04-06 17:46:22' WHERE config_id = 374;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'payment/banktransfer/min_order_total', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 375;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'payment/banktransfer/max_order_total', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 376;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'payment/banktransfer/sort_order', value = null, updated_at = '2025-04-06 17:46:22' WHERE config_id = 377;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/general/enabled', value = '1', updated_at = '2025-04-06 17:46:22' WHERE config_id = 378;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/general/api_key', value = 'AIzaSyAyqdYA2AZtc5Rqmcdn-0uSvdC5GL8mWtk', updated_at = '2025-04-06 17:46:23' WHERE config_id = 379;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/general/draggable', value = '1', updated_at = '2025-04-06 17:46:23' WHERE config_id = 380;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/general/map_type', value = 'roadmap', updated_at = '2025-04-06 17:46:23' WHERE config_id = 381;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/general/display_area', value = 'bottom', updated_at = '2025-04-14 14:47:26' WHERE config_id = 382;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/general/wrap_block', value = '1', updated_at = '2025-04-06 17:46:23' WHERE config_id = 383;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/coordinates/address', value = 'Garden Lawn & Irrigation Marcin Piechota', updated_at = '2025-04-15 15:38:39' WHERE config_id = 384;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/coordinates/latitude', value = '50.760640', updated_at = '2025-04-15 15:38:39' WHERE config_id = 385;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'amgooglemap/coordinates/longitude', value = '17.843079', updated_at = '2025-04-15 15:38:39' WHERE config_id = 386;
UPDATE magento.core_config_data SET scope = 'stores', scope_id = 3, path = 'design/theme/theme_id', value = '8', updated_at = '2025-04-06 18:13:34' WHERE config_id = 387;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/theme/theme_id', value = '2', updated_at = '2025-04-06 18:14:21' WHERE config_id = 388;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/pagination/pagination_frame', value = '5', updated_at = '2025-04-06 18:14:21' WHERE config_id = 389;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/pagination/pagination_frame_skip', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 390;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/pagination/anchor_text_for_previous', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 391;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/pagination/anchor_text_for_next', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 392;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/head/default_title', value = 'Magento Commerce', updated_at = '2025-04-06 18:14:21' WHERE config_id = 393;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/head/title_prefix', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 394;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/head/title_suffix', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 395;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/head/default_description', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 396;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/head/default_keywords', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 397;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/head/includes', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 398;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/head/demonotice', value = '0', updated_at = '2025-04-06 18:14:21' WHERE config_id = 399;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/header/logo_width', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 400;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/header/logo_height', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 401;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/header/logo_alt', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 402;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/header/welcome', value = 'Default welcome msg!', updated_at = '2025-04-06 18:14:21' WHERE config_id = 403;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/header/translate_title', value = '1', updated_at = '2025-04-06 18:14:21' WHERE config_id = 404;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/footer/copyright', value = 'Copyright © 2013-present Magento, Inc. All rights reserved.', updated_at = '2025-04-06 18:14:21' WHERE config_id = 405;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/footer/absolute_footer', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 406;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/footer/report_bugs', value = '1', updated_at = '2025-04-06 18:14:21' WHERE config_id = 407;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/search_engine_robots/default_robots', value = 'INDEX,FOLLOW', updated_at = '2025-04-06 18:14:21' WHERE config_id = 408;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/search_engine_robots/custom_instructions', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 409;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/image_size', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 410;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/image_imageOpacity', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 411;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/image_position', value = 'stretch', updated_at = '2025-04-06 18:14:21' WHERE config_id = 412;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/small_image_size', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 413;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/small_image_imageOpacity', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 414;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/small_image_position', value = 'stretch', updated_at = '2025-04-06 18:14:21' WHERE config_id = 415;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/thumbnail_size', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 416;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/thumbnail_imageOpacity', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 417;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/watermark/thumbnail_position', value = 'stretch', updated_at = '2025-04-06 18:14:21' WHERE config_id = 418;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/email/logo_alt', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 419;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/email/logo_width', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 420;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/email/logo_height', value = null, updated_at = '2025-04-06 18:14:21' WHERE config_id = 421;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/email/header_template', value = 'design_email_header_template', updated_at = '2025-04-06 18:14:21' WHERE config_id = 422;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'design/email/footer_template', value = 'design_email_footer_template', updated_at = '2025-04-06 18:14:21' WHERE config_id = 423;
UPDATE magento.core_config_data SET scope = 'websites', scope_id = 2, path = 'web/default/front', value = 'o-nas', updated_at = '2025-04-14 13:51:58' WHERE config_id = 424;
UPDATE magento.core_config_data SET scope = 'stores', scope_id = 4, path = 'web/default/front', value = 'o-nas', updated_at = '2025-04-14 13:52:14' WHERE config_id = 425;
UPDATE magento.core_config_data SET scope = 'websites', scope_id = 2, path = 'design/theme/theme_id', value = '6', updated_at = '2025-04-15 17:42:58' WHERE config_id = 426;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/rule/share_all_catalog_rules', value = '1', updated_at = '2025-04-15 18:52:56' WHERE config_id = 427;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/rule/share_applied_catalog_rules', value = '1', updated_at = '2025-04-15 18:52:56' WHERE config_id = 428;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/placeholder/image_placeholder', value = null, updated_at = '2025-04-15 18:52:56' WHERE config_id = 429;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/placeholder/small_image_placeholder', value = null, updated_at = '2025-04-15 18:52:56' WHERE config_id = 430;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/placeholder/thumbnail_placeholder', value = null, updated_at = '2025-04-15 18:52:56' WHERE config_id = 431;
UPDATE magento.core_config_data SET scope = 'default', scope_id = 0, path = 'catalog/placeholder/swatch_image_placeholder', value = null, updated_at = '2025-04-15 18:52:56' WHERE config_id = 432;
